In [ ]:
from pathlib import Path

BASE = Path().resolve().parent  # TRM_project/
OUT = BASE / "processed_data"
GRN = BASE / "GRN_SCENIC"
FIG = BASE / "figures_results"

In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 '.RData',
 '.Rhistory',
 '1770874032360blob.jpg',
 '1770894835322blob.jpg',
 '1770898193029blob.jpg',
 '1770898214264blob.jpg',
 '1770898248892blob.jpg',
 '1770900707679blob.jpg',
 'Ana brief final 500 line 20260211_0831.docx',
 'baseline_stability_curve.csv',
 'BCH01_Tcells_NL_vs_L.h5ad',
 'BCH01_TRM_NL_vs_L.h5ad',
 'Cell_Systems_Complete_Submission_Package.txt',
 'Cell_Systems_Formatting_Guide.txt',
 'Cell_Systems_Submission_Checklist.txt',
 'Classifier_Independence_Test.png',
 'Claude Setup.exe',
 'desktop.ini',
 'ESUN_Estatement_11501.pdf',
 'Figure1_regulon_attractor (1).png',
 'Figure1_regulon_attractor.pdf',
 'Figure1_regulon_attractor.png',
 'Figure1_regulon_attractor.svg',
 'Figure2_single_TF_perturbation.pdf',
 'Figure2_single_TF_perturbation.png',
 'Figure2_single_TF_perturbation.svg',
 'Figure3_pairwise_perturbation.pdf',
 'Figure3_pairwise_perturbation.png',
 'Figure3_pairwise_perturbation.svg',
 'Figure4_mechanistic_model.pdf',
 'Figure4_mechanistic_model.png',
 'Figure4_mechanistic_model.svg',
 'Figure5_theoretical_framework.pdf',
 'Figure5_theoretical_framework.png',
 'Figure5_theoretical_framework.svg',
 'figures',
 'Figure_Legends_Manuscript.txt',
 'figure_slide_1.png',
 'FINAL_Margin_Verdict.png',
 'GSE204765_RAW.tar',
 'GSM6190732_BCH01-NL1.h5ad',
 'GSM6190732_BCH01-NL1.h5ad.gz',
 'GSM6190732_BCH01-NL1.h5seurat',
 'GSM6190732_BCH01-NL1_obs.rds',
 'GSM6190734_BCH01-L1.h5ad',
 'GSM6190734_BCH01-L1.h5ad.gz',
 'GSM6190734_BCH01-L1_obs.rds',
 'hg38_10kb.rankings.feather',
 'hg38_tfs.txt',
 'hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.genes_vs_motifs.rankings.feather',
 'IL22TRMPOU2F1.ipynb',
 'leave_one_out_stability.csv',
 'locking_tf_rank.csv',
 'Miniconda3-latest-Windows-x86_64.exe',
 'motifs-v9-nr.hgnc-m0.001-o0.0.tbl',
 'motifs-v9-nr.hgnc-m0.001-o0.0.tbl.txt',
 'Screenshot_20260213-090745.png',
 'Screenshot_20260214-100722.png',
 'Screenshot_20260214-100804.png',
 'Screenshot_20260214-100818.png',
 'Screenshot_20260214-100832.png',
 'setup_pyscenic.sh',
 'SICAI_Blueprint_v1.docx',
 'skin co-author CFP 2026.2.11.xlsx',
 'Supplementary_Figure_S4_TF_network.pdf',
 'Supplementary_Figure_S4_TF_network.png',
 'Supplementary_Figure_S4_TF_network.svg',
 'Supplementary_Materials_Guide.txt',
 'Supplementary_Tables_S2_S3_templates.xlsx',
 'Table1_differential_regulons.csv',
 'Table1_single_TF_perturbation.csv',
 'Table2_pairwise_perturbation.csv',
 'Table2_single_TF_perturbation.csv',
 'Table3_pairwise_perturbation.csv',
 'tf_census.xlsx',
 'TOP_5_Cooperative_Pairs_FOR_PAPER.csv',
 'trm_auc.csv',
 'trm_expr.tsv',
 'trm_grn.csv',
 'trm_meta.tsv',
 'trm_regulons.csv',
 'trm_scanpy.py',
 'two_tf_most_damaging.csv',
 'two_tf_most_synergy.csv',
 'two_tf_removal_stability.csv',
 'Untitled.ipynb',
 'untitled.py',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb']

In [2]:
import pandas as pd
import numpy as np

auc = pd.read_csv(str(GRN / "trm_auc.csv"), index_col=0)

print(auc.shape)
auc.head()

(89, 32)

,CHD1(+),CXXC1(+),DBP(+),ELF1(+),ELK3(+),EOMES(+),ETS1(+),FLI1(+),FOSB(+),FOXK1(+),...,RUNX3(+),SP2(+),SP3(+),TCF7(+),XRCC4(+),ZBTB49(+),ZNF182(+),ZNF195(+),ZNF528(+),ZNF740(+)
Cell,,,,,,,,,,,,,,,,,,,,,
AACTTTCCAAGCCGCT-1-BCH01-L1,0.000000,0.040351,0.328333,0.014286,0.031950,0.039020,0.024794,0.032421,0.057222,0.000000,...,0.000000,0.032099,0.000000,0.0,0.006795,0.040833,0.238333,0.098333,0.000000,0.114333
AAGGAGCCAAGACACG-1-BCH01-L1,0.000000,0.000000,0.224167,0.011575,0.023774,0.042549,0.050487,0.047088,0.063611,0.000000,...,0.000000,0.081481,0.000000,0.0,0.052372,0.042917,0.000000,0.000000,0.114444,0.000000
AAGGCAGCAATCCAAC-1-BCH01-L1,0.000000,0.040702,0.000000,0.016215,0.046457,0.019412,0.045993,0.039298,0.046944,0.000000,...,0.000000,0.000000,0.000000,0.0,0.022821,0.161667,0.210000,0.000000,0.000000,0.103333
AAGTCTGTCCACGTTC-1-BCH01-L1,0.045625,0.000000,0.091667,0.019121,0.023522,0.020588,0.029588,0.013754,0.510000,0.154444,...,0.029111,0.052099,0.000000,0.0,0.006218,0.082083,0.000000,0.000000,0.228889,0.072333
ACATGGTTCTCTAAGG-1-BCH01-L1,0.000000,0.097193,0.000000,0.012381,0.037610,0.072353,0.009288,0.007930,0.031389,0.000000,...,0.059778,0.032593,0.131905,0.0,0.025321,0.100417,0.000000,0.117500,0.000000,0.087000

In [3]:
meta = pd.read_csv(str(OUT / "trm_meta.tsv"), sep="\t", index_col=0)

print(meta.columns)
meta.head()

Index(['10x_cell_calling', 'G2M_score', 'S_score', 'barcode_rank',
       'chemistry_10x', 'disease_status', 'empty_drops_FDR', 'ind_id',
       'lesional', 'log10_n_genes', 'log10_n_umis', 'mito_cutoff_', 'mt_frac',
       'n_counts', 'n_genes', 'n_umis', 'neg_log10_empty_drops_FDR', 'phase',
       'predicted_cell_types', 'sample_name', 'scrublet', 'scrublet_score',
       'sex', 'disease_lesional', 'batch', 'leiden', 'Cell type',
       'Cell type granular', 'ind_sample', 'channel', 'barcode', 'subject_id',
       'global_disease_assessment', 'ad_family_history', 'sex_clinical',
       'ethnicity_race', 'smoking', 'asthma', 'other_condition',
       'systemic_corticosteroids', 'topical_corticosteroids', 'dupilumab',
       'dupilumab_indication', 'dupilumab_other_indication', 'location',
       'side', 'Disease score (MADAD Immune)', 'Disease score (MADAD Full)',
       'Disease score (MADAD Union)', 'Cell type new cornified',
       'ind_disease_lesional', 'Cell states with PathT',
       'Cell type granular v2', 'Cell states with PathT v2', 'Compartment',
       'condition', 'n_genes_by_counts', 'log1p_n_genes_by_counts',
       'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes',
       'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes',
       'pct_counts_in_top_500_genes', 'total_counts_mt',
       'log1p_total_counts_mt', 'pct_counts_mt', 'score_Tcell', 'score_CD4',
       'score_CD8', 'score_TRMcore', 'score_Circ', 'lineage', 'IL22_high'],
      dtype='object')

,10x_cell_calling,G2M_score,S_score,barcode_rank,chemistry_10x,disease_status,empty_drops_FDR,ind_id,lesional,log10_n_genes,...,total_counts_mt,log1p_total_counts_mt,pct_counts_mt,score_Tcell,score_CD4,score_CD8,score_TRMcore,score_Circ,lineage,IL22_high
AGAATAGCACTTACGA-1-BCH01-NL1,True,-0.053953,-0.027792,6579.5,v2,AD,0.0,BCH01,No,2.642465,...,0.0,0.0,0.0,1.536042,0.000000,-0.077828,0.310986,-0.114008,CD4-like,False
AGCAGCCTCTGTCAAG-1-BCH01-NL1,True,-0.058431,0.281235,2438.5,v2,AD,0.0,BCH01,No,3.111599,...,0.0,0.0,0.0,1.083688,-0.206445,-0.229886,0.495793,-0.284491,CD4-like,False
CCGGTAGAGAAGGGTA-1-BCH01-NL1,True,-0.003505,-0.036166,7069.5,v2,AD,0.0,BCH01,No,2.594393,...,0.0,0.0,0.0,2.221469,0.000000,2.528250,0.397696,-0.237187,CD8-like,False
CGAATGTAGGATTCGG-1-BCH01-NL1,True,-0.059455,0.027260,6072.5,v2,AD,0.0,BCH01,No,2.704151,...,0.0,0.0,0.0,2.114978,-0.067436,0.982667,0.232075,-0.231757,CD8-like,False
CGATTGAGTTCACGGC-1-BCH01-NL1,True,-0.043114,-0.017598,7037.5,v2,AD,0.0,BCH01,No,2.630428,...,0.0,0.0,0.0,0.471156,1.230190,-0.100424,0.593210,-0.185269,CD4-like,False

In [4]:
# Make sure metadata index matches AUC index
auc = auc.loc[meta.index]

# Construct label
y = meta["IL22_high"].astype(int).values

# Construct X and tf_names
X = auc.values
tf_names = list(auc.columns)

print("Cells:", X.shape[0])
print("Features:", X.shape[1])
print("IL22-high:", sum(y))

Cells: 89
Features: 32
IL22-high: 9

In [5]:
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
import numpy as np

def compute_depth_cv(X, y, splits):
    margins = np.zeros(len(y))

    for train_idx, test_idx in splits:
        clf = LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="lbfgs",
            max_iter=2000,
            class_weight="balanced",
            random_state=0
        )
        clf.fit(X[train_idx], y[train_idx])

        w = clf.coef_[0]
        b = clf.intercept_[0]
        margins[test_idx] = (X[test_idx] @ w + b) / (np.linalg.norm(w) + 1e-12)

    return margins[y == 1].mean()

def compute_synergy_pair(X, y, splits, i, j):
    D0 = compute_depth_cv(X, y, splits)

    XA  = np.delete(X, i, axis=1)
    XB  = np.delete(X, j, axis=1)
    XAB = np.delete(X, [i, j], axis=1)

    DA  = compute_depth_cv(XA, y, splits)
    DB  = compute_depth_cv(XB, y, splits)
    DAB = compute_depth_cv(XAB, y, splits)

    dA  = D0 - DA
    dB  = D0 - DB
    dAB = D0 - DAB

In [6]:
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
import numpy as np

def compute_depth_cv(X, y, splits):
    margins = np.zeros(len(y))

    for train_idx, test_idx in splits:
        clf = LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="lbfgs",
            max_iter=2000,
            class_weight="balanced",
            random_state=0
        )
        clf.fit(X[train_idx], y[train_idx])

        w = clf.coef_[0]
        b = clf.intercept_[0]
        margins[test_idx] = (X[test_idx] @ w + b) / (np.linalg.norm(w) + 1e-12)

    return margins[y == 1].mean()

def compute_synergy_pair(X, y, splits, i, j):
    D0 = compute_depth_cv(X, y, splits)

    XA  = np.delete(X, i, axis=1)
    XB  = np.delete(X, j, axis=1)
    XAB = np.delete(X, [i, j], axis=1)

    DA  = compute_depth_cv(XA, y, splits)
    DB  = compute_depth_cv(XB, y, splits)
    DAB = compute_depth_cv(XAB, y, splits)

    dA  = D0 - DA
    dB  = D0 - DB
    dAB = D0 - DAB

    return dAB - (dA + dB)

# Prepare CV splits
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
splits = list(skf.split(X, y))

# Find indices
i = tf_names.index("CHD1(+)")
j = tf_names.index("RRBP5(+)")

# Observed synergy
synergy_obs = compute_synergy_pair(X, y, splits, i, j)

# Permutation null
rng = np.random.default_rng(20260214)
n_perms = 500
null = np.zeros(n_perms)

for p in range(n_perms):
    y_perm = rng.permutation(y)
    null[p] = compute_synergy_pair(X, y_perm, splits, i, j)

k = (null <= synergy_obs).sum()
pval = (k + 1) / (n_perms + 1)

print("=== CHD1–RRBP5 AUDIT ===")
print("Observed synergy:", synergy_obs)
print("Null min / median / max:", null.min(), np.median(null), null.max())
print("k:", k)
print("Permutation p:", pval)
print("First 10 null values:", null[:10])

ValueError: 'RRBP5(+)' is not in list

In [7]:
for name in tf_names:
    if "R" in name:
        print(name)

RBBP5(+)
REL(+)
RFX2(+)
RORA(+)
RUNX2(+)
RUNX3(+)
XRCC4(+)

In [8]:
i = tf_names.index("CHD1(+)")
j = tf_names.index("RBBP5(+)")

In [9]:
j = tf_names.index("RBBP5(+)")

In [10]:
Observed synergy:
Null min / median / max:
k:
Permutation p:
First 10 null values:

SyntaxError: invalid syntax (1455269300.py, line 1)

In [11]:
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
import numpy as np

def compute_depth_cv(X, y, splits):
    margins = np.zeros(len(y))
    for train_idx, test_idx in splits:
        clf = LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="lbfgs",
            max_iter=2000,
            class_weight="balanced",
            random_state=0
        )
        clf.fit(X[train_idx], y[train_idx])
        w = clf.coef_[0]
        b = clf.intercept_[0]
        margins[test_idx] = (X[test_idx] @ w + b) / (np.linalg.norm(w) + 1e-12)
    return margins[y == 1].mean()

def compute_synergy_pair(X, y, splits, i, j):
    D0 = compute_depth_cv(X, y, splits)
    XA  = np.delete(X, i, axis=1)
    XB  = np.delete(X, j, axis=1)
    XAB = np.delete(X, [i, j], axis=1)

    DA  = compute_depth_cv(XA, y, splits)
    DB  = compute_depth_cv(XB, y, splits)
    DAB = compute_depth_cv(XAB, y, splits)

    dA  = D0 - DA
    dB  = D0 - DB
    dAB = D0 - DAB

    return dAB - (dA + dB)

# Prepare CV

In [13]:
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
import numpy as np

def compute_depth_cv(X, y, splits):
    margins = np.zeros(len(y))
    for train_idx, test_idx in splits:
        clf = LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="lbfgs",
            max_iter=2000,
            class_weight="balanced",
            random_state=0
        )
        clf.fit(X[train_idx], y[train_idx])
        w = clf.coef_[0]
        b = clf.intercept_[0]
        margins[test_idx] = (X[test_idx] @ w + b) / (np.linalg.norm(w) + 1e-12)
    return margins[y == 1].mean()

def compute_synergy_pair(X, y, splits, i, j):
    D0 = compute_depth_cv(X, y, splits)
    XA  = np.delete(X, i, axis=1)
    XB  = np.delete(X, j, axis=1)
    XAB = np.delete(X, [i, j], axis=1)

    DA  = compute_depth_cv(XA, y, splits)
    DB  = compute_depth_cv(XB, y, splits)
    DAB = compute_depth_cv(XAB, y, splits)

    dA  = D0 - DA
    dB  = D0 - DB
    dAB = D0 - DAB

    return dAB - (dA + dB)

# Prepare CV splits
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
splits = list(skf.split(X, y))

# Correct indices
i = tf_names.index("CHD1(+)")
j = tf_names.index("RBBP5(+)")

# Observed synergy
synergy_obs = compute_synergy_pair(X, y, splits, i, j)

# Permutation null
rng = np.random.default_rng(20260214)
n_perms = 500
null = np.zeros(n_perms)

for p in range(n_perms):
    y_perm = rng.permutation(y)
    null[p] = compute_synergy_pair(X, y_perm, splits, i, j)

k = (null <= synergy_obs).sum()
pval = (k + 1) / (n_perms + 1)

print("=== CHD1–RBBP5 AUDIT ===")
print("Observed synergy:", synergy_obs)
print("Null min / median / max:", null.min(), np.median(null), null.max())
print("k:", k)
print("Permutation p:", pval)
print("First 10 null values:", null[:10])

=== CHD1–RBBP5 AUDIT ===
Observed synergy: -1.809737440373882e-05
Null min / median / max: -0.004410141466759554 -2.42651562454288e-07 0.004660801997262428
k: 193
Permutation p: 0.3872255489021956
First 10 null values: [-4.58187903e-05 -7.53046531e-07 -2.16897909e-05 -2.30837891e-05
  2.87708026e-04 -1.02384036e-03 -1.14221029e-04 -3.61692404e-04
  1.28096931e-04 -6.42204307e-05]

In [14]:
top16 = [
    "CHD1(+)", "ZNF395(+)", "FOXK1(+)", "RORA(+)", "RBBP5(+)",
    "REL(+)", "RUNX3(+)", "FOXO1(+)", "FOSL1(+)", "POLR4(+)",
    "IRF2(+)", "MYC(+)", "NOTCH1(+)", "RUNX2(+)", "OXSM(+)", "RAD3(+)"
]

# Subset matrix
X16 = auc[top16].values
tf16 = top16

print(X16.shape)

KeyError: "['ZNF395(+)', 'FOXO1(+)', 'FOSL1(+)', 'POLR4(+)', 'IRF2(+)', 'MYC(+)', 'NOTCH1(+)', 'OXSM(+)', 'RAD3(+)'] not in index"

In [15]:
import pandas as pd

diff = pd.read_csv("Table1_differential_regulons.csv")
print(diff.columns)
diff.head()

Index(['Transcription Factor', 'ΔAUC', 'P-value', '−log₁₀(P)'], dtype='object')

  Transcription Factor    ΔAUC   P-value  −log₁₀(P)
0            POU2F1(+)  0.0415  0.003011       2.52
1              RORA(+)  0.0339  0.006768       2.17
2            NFATC2(+)  0.0056  0.023885       1.62

In [16]:
# adjust column name if needed after you print diff.columns
reg_col = "Regulon" if "Regulon" in diff.columns else diff.columns[0]

top16 = diff.sort_values("Rank").head(16)[reg_col].tolist()
print("Top16 from file:")
print(top16)

# Now subset safely
missing = [x for x in top16 if x not in auc.columns]
print("Missing from auc:", missing)

X16 = auc[top16].values
tf16 = top16
print("X16 shape:", X16.shape)

KeyError: 'Rank'

In [17]:
# Sort by ΔAUC descending
top16 = diff.sort_values("ΔAUC", ascending=False).head(16)["Transcription Factor"].tolist()

print("Top16:")
print(top16)

# Check missing
missing = [x for x in top16 if x not in auc.columns]
print("Missing from AUC:", missing)

# Subset matrix
X16 = auc[top16].values
tf16 = top16

print("X16 shape:", X16.shape)

Top16:
['POU2F1(+)', 'RORA(+)', 'NFATC2(+)']
Missing from AUC: []
X16 shape: (89, 3)

In [18]:
import os

for f in os.listdir():
    if "auc" in f.lower():
        print(f)

trm_auc.csv

In [19]:
import pandas as pd

pair_files = [
    "Table3_pairwise_perturbation.csv",
    str(FIG / "two_tf_most_synergy.csv"),
    "two_tf_removal_stability.csv",
    "two_tf_most_damaging.csv",
    "TOP_5_Cooperative_Pairs_FOR_PAPER.csv",
    "Table2_pairwise_perturbation.csv",
]

for f in pair_files:
    try:
        df = pd.read_csv(f)
        print("\n===", f, "===")
        print(df.columns.tolist())
        print(df.head(3))
    except Exception as e:
        print("\n[skip]", f, "->", e)

=== Table3_pairwise_perturbation.csv ===
['Rank', 'TF 1', 'TF 2', 'ΔDepth (Pair)', 'Synergy', 'Expected (Additive)', 'Stability (Pair)']
   Rank       TF 1       TF 2  ΔDepth (Pair)  Synergy  Expected (Additive)  \
0     1  NFATC2(+)  POU2F1(+)            0.0      0.0                  0.0
1     2  NFATC2(+)    RORA(+)            0.0      0.0                  0.0
2     3  POU2F1(+)    RORA(+)            0.0      0.0                  0.0

   Stability (Pair)
0               1.0
1               1.0
2               1.0

=== two_tf_most_synergy.csv ===
['tf1', 'tf2', 'mean_stability_pair', 'delta_depth_vs_base', 'auc_pair', 'delta_auc_vs_base', 'expected_additive', 'synergy']
         tf1        tf2  mean_stability_pair  delta_depth_vs_base  auc_pair  \
0  POU2F1(+)   KDM5B(+)             0.667931            -0.049064  0.589841
1  POU2F1(+)  ZNF528(+)             0.670037            -0.046957  0.592640
2  POU2F1(+)    KLF2(+)             0.666386            -0.050609  0.588773

   delta_auc_vs_base  expected_additive   synergy
0          -0.410159           0.001049 -0.411208
1          -0.407360           0.002219 -0.409579
2          -0.411227          -0.001835 -0.409391

=== two_tf_removal_stability.csv ===
['tf1', 'tf2', 'mean_stability_pair', 'delta_depth_vs_base', 'auc_pair', 'delta_auc_vs_base', 'expected_additive', 'synergy']
         tf1      tf2  mean_stability_pair  delta_depth_vs_base  auc_pair  \
0  POU2F1(+)  FOSB(+)             0.675328            -0.041667  0.598081
1  POU2F1(+)  RORA(+)             0.683942            -0.033052  0.605094
2  POU2F1(+)   SP3(+)             0.681320            -0.035674  0.603193

   delta_auc_vs_base  expected_additive   synergy
0          -0.401919          -0.003848 -0.398071
1          -0.394906           0.000075 -0.394981
2          -0.396807          -0.000403 -0.396404

=== two_tf_most_damaging.csv ===
['tf1', 'tf2', 'mean_stability_pair', 'delta_depth_vs_base', 'auc_pair', 'delta_auc_vs_base', 'expected_additive', 'synergy']
         tf1       tf2  mean_stability_pair  delta_depth_vs_base  auc_pair  \
0  POU2F1(+)   KLF2(+)             0.666386            -0.050609  0.588773
1  POU2F1(+)  KDM5B(+)             0.667931            -0.049064  0.589841
2  POU2F1(+)    REL(+)             0.668446            -0.048549  0.591245

   delta_auc_vs_base  expected_additive   synergy
0          -0.411227          -0.001835 -0.409391
1          -0.410159           0.001049 -0.411208
2          -0.408755          -0.000290 -0.408464

=== TOP_5_Cooperative_Pairs_FOR_PAPER.csv ===
['TF 1', 'TF 2', 'ΔDepth (Pair)', 'Synergy', 'Expected (Additive)']
       TF 1      TF 2  ΔDepth (Pair)   Synergy  Expected (Additive)
0   CHD1(+)  RBBP5(+)       0.272376 -0.077901             0.350277
1   CHD1(+)    REL(+)       0.282618 -0.069448             0.352066
2  FOXK1(+)   RORA(+)       0.257766 -0.039695             0.297461

=== Table2_pairwise_perturbation.csv ===
['tf1', 'tf2', 'delta_depth', 'synergy', 'expected_additive', 'pair_auc']
         tf1        tf2  delta_depth  synergy  expected_additive  pair_auc
0  NFATC2(+)  POU2F1(+)          0.0      0.0                0.0       1.0
1  NFATC2(+)    RORA(+)          0.0      0.0                0.0       1.0
2  POU2F1(+)    RORA(+)          0.0      0.0                0.0       1.0

In [20]:
df = pd.read_csv(str(FIG / "two_tf_most_synergy.csv"))
print(df.columns)
print(df.head())

Index(['tf1', 'tf2', 'mean_stability_pair', 'delta_depth_vs_base', 'auc_pair',
       'delta_auc_vs_base', 'expected_additive', 'synergy'],
      dtype='object')
         tf1        tf2  mean_stability_pair  delta_depth_vs_base  auc_pair  \
0  POU2F1(+)   KDM5B(+)             0.667931            -0.049064  0.589841
1  POU2F1(+)  ZNF528(+)             0.670037            -0.046957  0.592640
2  POU2F1(+)    KLF2(+)             0.666386            -0.050609  0.588773
3  POU2F1(+)  NFATC2(+)             0.669101            -0.047893  0.591442
4  POU2F1(+)     SP2(+)             0.671489            -0.045506  0.592313

   delta_auc_vs_base  expected_additive   synergy
0          -0.410159           0.001049 -0.411208
1          -0.407360           0.002219 -0.409579
2          -0.411227          -0.001835 -0.409391
3          -0.408558           0.000721 -0.409279
4          -0.407687           0.001423 -0.409110

In [21]:
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
import numpy as np

def compute_auc_cv(X, y, splits):
    probs = np.zeros(len(y))
    for train_idx, test_idx in splits:
        clf = LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="lbfgs",
            max_iter=2000,
            class_weight="balanced",
            random_state=0
        )
        clf.fit(X[train_idx], y[train_idx])
        probs[test_idx] = clf.predict_proba(X[test_idx])[:, 1]
    return roc_auc_score(y, probs)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
splits = list(skf.split(X, y))

# baseline AUC
auc_base = compute_auc_cv(X, y, splits)

# indices
i = tf_names.index("CHD1(+)")
j = tf_names.index("RBBP5(+)")

# remove A
X_A = np.delete(X, i, axis=1)
auc_A = compute_auc_cv(X_A, y, splits)

# remove B
X_B = np.delete(X, j, axis=1)
auc_B = compute_auc_cv(X_B, y, splits)

# remove both
X_AB = np.delete(X, [i, j], axis=1)
auc_AB = compute_auc_cv(X_AB, y, splits)

delta_A = auc_base - auc_A
delta_B = auc_base - auc_B
delta_AB = auc_base - auc_AB

expected = delta_A + delta_B
synergy = delta_AB - expected

print("AUC base:", auc_base)
print("delta_A:", delta_A)
print("delta_B:", delta_B)
print("delta_AB:", delta_AB)
print("Expected additive:", expected)
print("Synergy:", synergy)

AUC base: 0.5680555555555555
delta_A: -0.011111111111111183
delta_B: 0.005555555555555536
delta_AB: -0.001388888888888884
Expected additive: -0.005555555555555647
Synergy: 0.004166666666666763

In [22]:
import os
for f in os.listdir():
    if f.endswith(".csv") or f.endswith(".tsv"):
        print(f)

baseline_stability_curve.csv
leave_one_out_stability.csv
locking_tf_rank.csv
Table1_differential_regulons.csv
Table1_single_TF_perturbation.csv
Table2_pairwise_perturbation.csv
Table2_single_TF_perturbation.csv
Table3_pairwise_perturbation.csv
TOP_5_Cooperative_Pairs_FOR_PAPER.csv
trm_auc.csv
trm_expr.tsv
trm_grn.csv
trm_meta.tsv
trm_regulons.csv
two_tf_most_damaging.csv
two_tf_most_synergy.csv
two_tf_removal_stability.csv

In [23]:
reg = pd.read_csv(str(GRN / "trm_regulons.csv"), index_col=0)
print(reg.shape)
reg.head()

(679, 9)

,Unnamed: 1,Enrichment,Enrichment.1,Enrichment.2,Enrichment.3,Enrichment.4,Enrichment.5,Enrichment.6,Enrichment.7
NaN,NaN,AUC,NES,MotifSimilarityQvalue,OrthologousIdentity,Annotation,Context,TargetGenes,RankAtMax
TF,MotifID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHD1,transfac_pro__M04787,0.07134795288414196,3.1409838205780156,7.4e-05,1.0,motif similar to dbcorrdb__CHD1__ENCSR000EFC_1...,"frozenset({'activating', 'hg38__refseq-r80__10...","[('XRCC1', 4.4273635940705685), ('BIRC3', 0.90...",1634
ELF1,predrem__nrMotif2167,0.04944969513888118,3.0883645615729933,0.000785,1.0,gene is annotated for similar motif dbcorrdb__...,"frozenset({'activating', 'hg38__refseq-r80__10...","[('TBC1D23', 7.939686147352721), ('DHX40', 0.2...",999
ELF1,dbcorrdb__RBBP5__ENCSR000AQC_1__m5,0.05520448092165421,3.928609057991084,0.000625,1.0,motif similar to dbcorrdb__ELF1__ENCSR000BPT_1...,"frozenset({'activating', 'hg38__refseq-r80__10...","[('EPSTI1', 0.8879742709729483), ('SOCS1', 3.1...",905

In [24]:
reg = reg.loc[meta.index]
X_reg = reg.values
print("Cells:", X_reg.shape[0])
print("Features:", X_reg.shape[1])

KeyError: "None of [Index(['AGAATAGCACTTACGA-1-BCH01-NL1', 'AGCAGCCTCTGTCAAG-1-BCH01-NL1',\n       'CCGGTAGAGAAGGGTA-1-BCH01-NL1', 'CGAATGTAGGATTCGG-1-BCH01-NL1',\n       'CGATTGAGTTCACGGC-1-BCH01-NL1', 'CGGACGTAGTGCGATG-1-BCH01-NL1',\n       'GAAACTCTCAGCAACT-1-BCH01-NL1', 'GCGCAGTCAACTGGCC-1-BCH01-NL1',\n       'GGCGACTAGCCAGGAT-1-BCH01-NL1', 'GTCTTCGTCTACTTAC-1-BCH01-NL1',\n       'GTGCATACATGTCCTC-1-BCH01-NL1', 'TATGCCCCACCAGGTC-1-BCH01-NL1',\n       'TCCCGATTCCGCAGTG-1-BCH01-NL1', 'TCTGAGAAGCTGAAAT-1-BCH01-NL1',\n       'GTACTTTCATGACGGA-1-BCH01-L1', 'GTCATTTAGGATGGTC-1-BCH01-L1',\n       'TATCTCACACCAGATT-1-BCH01-L1', 'TCGCGTTTCTAACTGG-1-BCH01-L1',\n       'AACTTTCCAAGCCGCT-1-BCH01-L1', 'AAGGAGCCAAGACACG-1-BCH01-L1',\n       'AAGGCAGCAATCCAAC-1-BCH01-L1', 'ACATGGTTCTCTAAGG-1-BCH01-L1',\n       'ACGAGCCAGTACGACG-1-BCH01-L1', 'ACGGAGATCAACACAC-1-BCH01-L1',\n       'ACTGAACCACCCATTC-1-BCH01-L1', 'ACTGATGGTACCGCTG-1-BCH01-L1',\n       'AGCCTAAAGGGCTTCC-1-BCH01-L1', 'AGCTCCTTCAAGGCTT-1-BCH01-L1',\n       'AGGCCGTTCCAATGGT-1-BCH01-L1', 'ATCATCTGTGTTCTTT-1-BCH01-L1',\n       'ATGAGGGCAGTGGGAT-1-BCH01-L1', 'ATGGGAGCAGTGGGAT-1-BCH01-L1',\n       'CACAAACGTGAGTATA-1-BCH01-L1', 'CACACCTGTTTGACTG-1-BCH01-L1',\n       'CACACTCTCAACACCA-1-BCH01-L1', 'CACCAGGCAAGTAATG-1-BCH01-L1',\n       'CAGAGAGCATGACATC-1-BCH01-L1', 'CATATGGGTAGGAGTC-1-BCH01-L1',\n       'CATATTCCATCGTCGG-1-BCH01-L1', 'CATATTCCATGATCCA-1-BCH01-L1',\n       'CATCAAGGTCTCACCT-1-BCH01-L1', 'CATGCCTGTCTAGAGG-1-BCH01-L1',\n       'CCATGTCAGTACGCGA-1-BCH01-L1', 'CGATGTAAGACGACGT-1-BCH01-L1',\n       'CGCCAAGGTATATGGA-1-BCH01-L1', 'CGGACACCAGATGAGC-1-BCH01-L1',\n       'CGGAGCTCAACGATGG-1-BCH01-L1', 'CGGTTAAAGTCGATAA-1-BCH01-L1',\n       'CGTAGGCTCTACTATC-1-BCH01-L1', 'CGTCTACAGATTACCC-1-BCH01-L1',\n       'CGTGAGCAGCCAGTTT-1-BCH01-L1', 'CGTGAGCTCATGTAGC-1-BCH01-L1',\n       'CGTGTCTTCAATAAGG-1-BCH01-L1', 'CTACATTCACCGCTAG-1-BCH01-L1',\n       'CTAGTGAAGCACACAG-1-BCH01-L1', 'CTCCTAGGTGGGTCAA-1-BCH01-L1',\n       'CTCGGAGAGCAAATCA-1-BCH01-L1', 'CTGAAGTGTCGAACAG-1-BCH01-L1',\n       'CTGATCCGTCAGGACA-1-BCH01-L1', 'CTTGGCTAGAAGGTGA-1-BCH01-L1',\n       'CTTTGCGAGCTTCGCG-1-BCH01-L1', 'CTTTGCGCAAACAACA-1-BCH01-L1',\n       'GACTACAAGATCCGAG-1-BCH01-L1', 'GATCGATCAGCTTCGG-1-BCH01-L1',\n       'GCAAACTTCACTCTTA-1-BCH01-L1', 'GGAAAGCGTGCTAGCC-1-BCH01-L1',\n       'GGATGTTTCTCTAGGA-1-BCH01-L1', 'GGATTACAGAATTCCC-1-BCH01-L1',\n       'GGCGACTTCTTGTTTG-1-BCH01-L1', 'GGGTTGCGTTATGTGC-1-BCH01-L1',\n       'GTATCTTCAGCTCCGA-1-BCH01-L1', 'GTCATTTTCAAGCCTA-1-BCH01-L1',\n       'GTTAAGCAGCTAAGAT-1-BCH01-L1', 'GTTAAGCCATCACGTA-1-BCH01-L1',\n       'TATCTCAGTAAACCTC-1-BCH01-L1', 'TCACAAGAGACAATAC-1-BCH01-L1',\n       'TGACTTTAGAAACCTA-1-BCH01-L1', 'TGAGGGAAGCTAACTC-1-BCH01-L1',\n       'TGGCTGGCAGGTCTCG-1-BCH01-L1', 'TGGTTAGCATGTAAGA-1-BCH01-L1',\n       'TGTTCCGCATCTCCCA-1-BCH01-L1', 'TGTTCCGGTCTAGTGT-1-BCH01-L1',\n       'TTAGGACTCACTTCAT-1-BCH01-L1', 'TTATGCTTCTACTCAT-1-BCH01-L1',\n       'TTGGCAACAATGCCAT-1-BCH01-L1', 'TTGTAGGCAGATGGCA-1-BCH01-L1',\n       'AAGTCTGTCCACGTTC-1-BCH01-L1', 'ATGTGTGCAGTAAGAT-1-BCH01-L1',\n       'CTGTGCTTCTGACCTC-1-BCH01-L1'],\n      dtype='object')] are in the [index]"

In [25]:
df = pd.read_csv(str(FIG / "two_tf_most_synergy.csv"))

# approximate baseline AUC from first row
auc_base_est = df.loc[0, "delta_auc_vs_base"] + df.loc[0, "auc_pair"]
print("Estimated baseline AUC from CSV:", auc_base_est)

Estimated baseline AUC from CSV: 0.17968164794007496

In [26]:
import pandas as pd
import numpy as np

df = pd.read_csv(str(FIG / "two_tf_most_synergy.csv"))

# Show first few rows with key columns
cols = ["tf1","tf2","auc_pair","delta_auc_vs_base","delta_depth_vs_base","expected_additive","synergy","mean_stability_pair"]
print(df[cols].head(10))

# Check if synergy is defined as delta_auc_vs_base - expected_additive
check = df["delta_auc_vs_base"] - df["expected_additive"]
print("\nMax |(delta_auc_vs_base - expected_additive) - synergy|:",
      np.max(np.abs(check - df["synergy"])))

         tf1        tf2  auc_pair  delta_auc_vs_base  delta_depth_vs_base  \
0  POU2F1(+)   KDM5B(+)  0.589841          -0.410159            -0.049064
1  POU2F1(+)  ZNF528(+)  0.592640          -0.407360            -0.046957
2  POU2F1(+)    KLF2(+)  0.588773          -0.411227            -0.050609
3  POU2F1(+)  NFATC2(+)  0.591442          -0.408558            -0.047893
4  POU2F1(+)     SP2(+)  0.592313          -0.407687            -0.045506
5  POU2F1(+)     REL(+)  0.591245          -0.408755            -0.048549
6   KDM5B(+)     SP2(+)  0.593109          -0.406891            -0.044429
7     REL(+)     SP2(+)  0.591798          -0.408202            -0.046489
8  ZNF528(+)    KLF2(+)  0.591779          -0.408221            -0.046816
9  ZNF528(+)   KDM5B(+)  0.594785          -0.405215            -0.044429

   expected_additive   synergy  mean_stability_pair
0           0.001049 -0.411208             0.667931
1           0.002219 -0.409579             0.670037
2          -0.001835 -0.409391             0.666386
3           0.000721 -0.409279             0.669101
4           0.001423 -0.409110             0.671489
5          -0.000290 -0.408464             0.668446
6           0.001367 -0.408258             0.672566
7           0.000028 -0.408230             0.670506
8          -0.000721 -0.407500             0.670178
9           0.002163 -0.407378             0.672566

Max |(delta_auc_vs_base - expected_additive) - synergy|: 1.1102230246251565e-16

In [27]:
auc_base_est2 = df.loc[0,"auc_pair"] - df.loc[0,"delta_auc_vs_base"]
print("Baseline AUC if delta = (auc_pair - auc_base):", auc_base_est2)

Baseline AUC if delta = (auc_pair - auc_base): 1.0

In [28]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Load top 5 cooperative pairs
top5 = pd.read_csv("TOP_5_Cooperative_Pairs_FOR_PAPER.csv")
pairs = list(zip(top5["TF 1"], top5["TF 2"]))

# Reconstruct the original 16-TF feature set
# Use unique TFs appearing in top5 and in previous outputs
tf16 = sorted(list(set(top5["TF 1"]).union(set(top5["TF 2"]))))

# If that gives fewer than 16, expand from differential table
if len(tf16) < 16:
    diff = pd.read_csv("Table1_differential_regulons.csv")
    tf16 = diff.sort_values("ΔAUC", ascending=False)["Transcription Factor"].head(16).tolist()

# Ensure all are present in auc
tf16 = [tf for tf in tf16 if tf in auc.columns]

X16 = auc[tf16].values
print("Using feature set size:", X16.shape[1])

# CV setup
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
splits = list(skf.split(X16, y))

def compute_auc_cv(X, y, splits):
    probs = np.zeros(len(y))
    for train_idx, test_idx in splits:
        clf = LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="lbfgs",
            max_iter=2000,
            class_weight="balanced",
            random_state=0
        )
        clf.fit(X[train_idx], y[train_idx])
        probs[test_idx] = clf.predict_proba(X[test_idx])[:, 1]
    return roc_auc_score(y, probs)

# Baseline AUC
auc_base = compute_auc_cv(X16, y, splits)
print("Baseline CV AUC:", auc_base)

# Compute synergy for each top pair
results = []

for tf1, tf2 in pairs:
    if tf1 not in tf16 or tf2 not in tf16:
        continue

    i = tf16.index(tf1)
    j = tf16.index(tf2)

    X_A = np.delete(X16, i, axis=1)
    X_B = np.delete(X16, j, axis=1)
    X_AB = np.delete(X16, [i, j], axis=1)

    auc_A = compute_auc_cv(X_A, y, splits)
    auc_B = compute_auc_cv(X_B, y, splits)
    auc_AB = compute_auc_cv(X_AB, y, splits)

    delta_A = auc_base - auc_A
    delta_B = auc_base - auc_B
    delta_AB = auc_base - auc_AB

    expected = delta_A + delta_B
    synergy = delta_AB - expected

    results.append((tf1, tf2, synergy))

print("\nCV-based synergy estimates (Top 5 pairs):")
for r in results:
    print(r)

Using feature set size: 3
Baseline CV AUC: 0.8222222222222222

CV-based synergy estimates (Top 5 pairs):

In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Load top 5 cooperative pairs
top5 = pd.read_csv("TOP_5_Cooperative_Pairs_FOR_PAPER.csv")
pairs = list(zip(top5["TF 1"], top5["TF 2"]))

# Reconstruct the original 16-TF feature set
# Use unique TFs appearing in top5 and in previous outputs
tf16 = sorted(list(set(top5["TF 1"]).union(set(top5["TF 2"]))))

# If that gives fewer than 16, expand from differential table
if len(tf16) < 16:
    diff = pd.read_csv("Table1_differential_regulons.csv")
    tf16 = diff.sort_values("ΔAUC", ascending=False)["Transcription Factor"].head(16).tolist()

# Ensure all are present in auc
tf16 = [tf for tf in tf16 if tf in auc.columns]

X16 = auc[tf16].values
print("Using feature set size:", X16.shape[1])

# CV setup
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
splits = list(skf.split(X16, y))

def compute_auc_cv(X, y, splits):
    probs = np.zeros(len(y))
    for train_idx, test_idx in splits:
        clf = LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="lbfgs",
            max_iter=2000,
            class_weight="balanced",
            random_state=0
        )
        clf.fit(X[train_idx], y[train_idx])
        probs[test_idx] = clf.predict_proba(X[test_idx])[:, 1]
    return roc_auc_score(y, probs)

# Baseline AUC
auc_base = compute_auc_cv(X16, y, splits)
print("Baseline CV AUC:", auc_base)

# Compute synergy for each top pair
results = []

for tf1, tf2 in pairs:
    if tf1 not in tf16 or tf2 not in tf16:
        continue

    i = tf16.index(tf1)
    j = tf16.index(tf2)

    X_A = np.delete(X16, i, axis=1)
    X_B = np.delete(X16, j, axis=1)
    X_AB = np.delete(X16, [i, j], axis=1)

    auc_A = compute_auc_cv(X_A, y, splits)
    auc_B = compute_auc_cv(X_B, y, splits)
    auc_AB = compute_auc_cv(X_AB, y, splits)

    delta_A = auc_base - auc_A
    delta_B = auc_base - auc_B
    delta_AB = auc_base - auc_AB

    expected = delta_A + delta_B
    synergy = delta_AB - expected

    results.append((tf1, tf2, synergy))

print("\nCV-based synergy estimates (Top 5 pairs):")
for r in results:
    print(r)

Using feature set size: 3
Baseline CV AUC: 0.8222222222222222

CV-based synergy estimates (Top 5 pairs):

In [30]:
print(sorted(auc.columns.tolist()))

['CHD1(+)', 'CXXC1(+)', 'DBP(+)', 'ELF1(+)', 'ELK3(+)', 'EOMES(+)', 'ETS1(+)', 'FLI1(+)', 'FOSB(+)', 'FOXK1(+)', 'FOXP4(+)', 'IKZF3(+)', 'KDM5A(+)', 'KDM5B(+)', 'KLF2(+)', 'NFATC2(+)', 'POU2F1(+)', 'RBBP5(+)', 'REL(+)', 'RFX2(+)', 'RORA(+)', 'RUNX2(+)', 'RUNX3(+)', 'SP2(+)', 'SP3(+)', 'TCF7(+)', 'XRCC4(+)', 'ZBTB49(+)', 'ZNF182(+)', 'ZNF195(+)', 'ZNF528(+)', 'ZNF740(+)']

In [31]:
import pandas as pd

files = [
    str(FIG / "two_tf_most_synergy.csv"),
    "two_tf_removal_stability.csv",
    "two_tf_most_damaging.csv",
    "TOP_5_Cooperative_Pairs_FOR_PAPER.csv"
]

tf_set = set()

for f in files:
    df = pd.read_csv(f)
    cols = df.columns
    
    # handle different column names
    if "tf1" in cols:
        tf_set.update(df["tf1"].tolist())
        tf_set.update(df["tf2"].tolist())
    if "TF 1" in cols:
        tf_set.update(df["TF 1"].tolist())
        tf_set.update(df["TF 2"].tolist())

tf_list = sorted(list(tf_set))
print("Number of TFs used in cooperative analysis:", len(tf_list))
print(tf_list)

Number of TFs used in cooperative analysis: 20
['CHD1(+)', 'CXXC1(+)', 'DBP(+)', 'ELK3(+)', 'FOSB(+)', 'FOXK1(+)', 'FOXP4(+)', 'KDM5B(+)', 'KLF2(+)', 'NFATC2(+)', 'POU2F1(+)', 'RBBP5(+)', 'REL(+)', 'RORA(+)', 'RUNX2(+)', 'SP2(+)', 'SP3(+)', 'ZBTB49(+)', 'ZNF195(+)', 'ZNF528(+)']

In [32]:
tf16 = [tf for tf in tf_list if tf in auc.columns]
print("TFs present in auc:", len(tf16))

X16 = auc[tf16].values
print("X16 shape:", X16.shape)

TFs present in auc: 20
X16 shape: (89, 20)

In [33]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
import pandas as pd

# Load the top 5 pairs
top5 = pd.read_csv("TOP_5_Cooperative_Pairs_FOR_PAPER.csv")
pairs = list(zip(top5["TF 1"], top5["TF 2"]))

# CV splits
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
splits = list(skf.split(X16, y))

def compute_auc_cv(X, y, splits):
    probs = np.zeros(len(y))
    for tr, te in splits:
        clf = LogisticRegression(
            C=1.0, solver="lbfgs", max_iter=2000,
            class_weight="balanced", random_state=0
        )
        clf.fit(X[tr], y[tr])
        probs[te] = clf.predict_proba(X[te])[:, 1]
    return roc_auc_score(y, probs)

auc_base = compute_auc_cv(X16, y, splits)
print("Baseline CV AUC (20 TFs):", auc_base)

def synergy_for_pair(tf1, tf2):
    i = tf16.index(tf1)
    j = tf16.index(tf2)
    X_A  = np.delete(X16, i, axis=1)
    X_B  = np.delete(X16, j, axis=1)
    X_AB = np.delete(X16, [i, j], axis=1)

    auc_A  = compute_auc_cv(X_A, y, splits)
    auc_B  = compute_auc_cv(X_B, y, splits)
    auc_AB = compute_auc_cv(X_AB, y, splits)

    dA  = auc_base - auc_A
    dB  = auc_base - auc_B
    dAB = auc_base - auc_AB
    return dAB - (dA + dB)

print("\nCV-based synergy (Top 5 pairs):")
for tf1, tf2 in pairs:
    if tf1 in tf16 and tf2 in tf16:
        syn = synergy_for_pair(tf1, tf2)
        print(f"{tf1} -- {tf2}: {syn:.6f}")
    else:
        print(f"{tf1} -- {tf2}: (missing from tf16)")

Baseline CV AUC (20 TFs): 0.5541666666666667

CV-based synergy (Top 5 pairs):
CHD1(+) -- RBBP5(+): 0.002778
CHD1(+) -- REL(+): 0.000000
FOXK1(+) -- RORA(+): 0.002778
FOXK1(+) -- RBBP5(+): 0.009722
ZNF195(+) -- RORA(+): -0.004167

In [34]:
import numpy as np

# Suppose you have IL22 expression in meta['IL22'] or similar
il22 = meta["IL22_expr"].values  # adjust column name

q33, q67 = np.quantile(il22, [1/3, 2/3])
keep = (il22 <= q33) | (il22 >= q67)

y_tertile = np.full_like(il22, fill_value=-1, dtype=int)
y_tertile[il22 <= q33] = 0
y_tertile[il22 >= q67] = 1

X_keep = X[keep]
y_keep = y_tertile[keep]

KeyError: 'IL22_expr'

In [35]:
print(meta.columns.tolist())

['10x_cell_calling', 'G2M_score', 'S_score', 'barcode_rank', 'chemistry_10x', 'disease_status', 'empty_drops_FDR', 'ind_id', 'lesional', 'log10_n_genes', 'log10_n_umis', 'mito_cutoff_', 'mt_frac', 'n_counts', 'n_genes', 'n_umis', 'neg_log10_empty_drops_FDR', 'phase', 'predicted_cell_types', 'sample_name', 'scrublet', 'scrublet_score', 'sex', 'disease_lesional', 'batch', 'leiden', 'Cell type', 'Cell type granular', 'ind_sample', 'channel', 'barcode', 'subject_id', 'global_disease_assessment', 'ad_family_history', 'sex_clinical', 'ethnicity_race', 'smoking', 'asthma', 'other_condition', 'systemic_corticosteroids', 'topical_corticosteroids', 'dupilumab', 'dupilumab_indication', 'dupilumab_other_indication', 'location', 'side', 'Disease score (MADAD Immune)', 'Disease score (MADAD Full)', 'Disease score (MADAD Union)', 'Cell type new cornified', 'ind_disease_lesional', 'Cell states with PathT', 'Cell type granular v2', 'Cell states with PathT v2', 'Compartment', 'condition', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'score_Tcell', 'score_CD4', 'score_CD8', 'score_TRMcore', 'score_Circ', 'lineage', 'IL22_high']

In [36]:
expr = pd.read_csv(str(OUT / "trm_expr.tsv"), sep="\t", index_col=0)
print(expr.shape)
print("IL22" in expr.columns)

(89, 3000)
True

In [37]:
print(expr["IL22"].head())

AGAATAGCACTTACGA-1-BCH01-NL1   -0.221293
AGCAGCCTCTGTCAAG-1-BCH01-NL1   -0.221293
CCGGTAGAGAAGGGTA-1-BCH01-NL1   -0.221293
CGAATGTAGGATTCGG-1-BCH01-NL1   -0.221293
CGATTGAGTTCACGGC-1-BCH01-NL1   -0.221293
Name: IL22, dtype: float64

In [38]:
import pandas as pd

expr = pd.read_csv(str(OUT / "trm_expr.tsv"), sep="\t", index_col=0)

print("Expression matrix shape:", expr.shape)
print("First 20 genes:")
print(expr.columns[:20])

Expression matrix shape: (89, 3000)
First 20 genes:
Index(['A1BG', 'A1BG-AS1', 'A2M', 'AADAC', 'AAK1', 'AARS', 'AARS2', 'ABCC5',
       'ABCD1', 'ABCG1', 'ABHD1', 'ABHD12B', 'ABHD14A', 'ABI3', 'AC002331.1',
       'AC002467.7', 'AC003075.4', 'AC004076.5', 'AC004540.5', 'AC005954.4'],
      dtype='object')

In [39]:
print("Does IL22 exist?", "IL22" in expr.columns)

Does IL22 exist? True

In [40]:
import matplotlib.pyplot as plt

plt.hist(il22, bins=30)
plt.title("IL22 expression distribution")
plt.xlabel("Expression")
plt.ylabel("Cell count")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [41]:
il22 = expr["IL22"]
print(il22.describe())
print("\nNumber of unique values:", il22.nunique())
print("\nValue counts (top 10):")
print(il22.value_counts().head(10))
print("\nHow many cells above median:", (il22 > il22.median()).sum())
print("How many cells at the mode:", (il22 == il22.mode()[0]).sum())

count    89.000000
mean      0.393166
std       1.672892
min      -0.221293
25%      -0.221293
50%      -0.221293
75%      -0.221293
max       8.312412
Name: IL22, dtype: float64

Number of unique values: 13

Value counts (top 10):
-0.221293    77
 4.012786     1
 5.225986     1
 2.380764     1
 2.790071     1
 3.636217     1
 5.528818     1
 4.164717     1
 4.296474     1
 8.312412     1
Name: IL22, dtype: int64

How many cells above median: 12
How many cells at the mode: 77

In [42]:
import numpy as np
import pandas as pd
from dataclasses import dataclass
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from scipy.stats import norm

# ----------------------------
# Utilities
# ----------------------------
def make_balanced_labels(n_total=89, n_pos=9, rng=None):
    rng = np.random.default_rng() if rng is None else rng
    y = np.zeros(n_total, dtype=int)
    pos_idx = rng.choice(n_total, size=n_pos, replace=False)
    y[pos_idx] = 1
    return y

def simulate_X_with_interaction(y, p=20, gamma=0.0, w_main=1.0, noise=1.0, rng=None):
    """
    Generate features X with two special features A,B (cols 0,1).
    Additive part: w_main*A + w_main*B
    Cooperative part: gamma*(A*B)
    Labels are fixed (we condition on y) by shifting the mean of (A,B) for positives.
    
    This construction ensures a planted interaction signal while keeping control.
    """
    rng = np.random.default_rng() if rng is None else rng
    n = len(y)
    X = rng.normal(0, noise, size=(n, p))

    # Two "signal" features
    A = rng.normal(0, noise, size=n)
    B = rng.normal(0, noise, size=n)

    # Shift means for positives to create baseline separability + allow interaction to matter
    # This controls baseline AUC.
    A = A + (y * 1.0)  # mean shift for positives
    B = B + (y * 1.0)

    # Inject interaction structure by adding gamma*(A*B) into an additional hidden score dimension
    # and then pushing it back into A and B so a linear model "feels" it indirectly.
    # (Margin-depth version will also be sensitive because geometry changes.)
    interaction = (A * B)
    A = A + gamma * (interaction - interaction.mean())
    B = B + gamma * (interaction - interaction.mean())

    X[:, 0] = A
    X[:, 1] = B
    return X

def cv_predict_proba(X, y, splits, C=1.0, seed=0):
    probs = np.zeros(len(y), dtype=float)
    for tr, te in splits:
        clf = LogisticRegression(
            C=C, penalty="l2", solver="lbfgs", max_iter=5000,
            class_weight="balanced", random_state=seed
        )
        clf.fit(X[tr], y[tr])
        probs[te] = clf.predict_proba(X[te])[:, 1]
    return probs

def in_sample_predict_proba(X, y, C=1.0, seed=0):
    clf = LogisticRegression(
        C=C, penalty="l2", solver="lbfgs", max_iter=5000,
        class_weight="balanced", random_state=seed
    )
    clf.fit(X, y)
    return clf.predict_proba(X)[:, 1], clf

def auc_synergy(X, y, splits, i, j, mode="cv"):
    """
    Compute AUC-based synergy for pair (i,j).
    mode: "cv" uses out-of-fold probs; "insample" uses training probs.
    """
    if mode == "cv":
        p0 = cv_predict_proba(X, y, splits)
        auc0 = roc_auc_score(y, p0)

        XA  = np.delete(X, i, axis=1)
        XB  = np.delete(X, j, axis=1)
        XAB = np.delete(X, [i, j], axis=1)

        pA  = cv_predict_proba(XA, y, splits)
        pB  = cv_predict_proba(XB, y, splits)
        pAB = cv_predict_proba(XAB, y, splits)

        aucA  = roc_auc_score(y, pA)
        aucB  = roc_auc_score(y, pB)
        aucAB = roc_auc_score(y, pAB)

    elif mode == "insample":
        p0, _ = in_sample_predict_proba(X, y)
        auc0 = roc_auc_score(y, p0)

        XA  = np.delete(X, i, axis=1)
        XB  = np.delete(X, j, axis=1)
        XAB = np.delete(X, [i, j], axis=1)

        pA, _  = in_sample_predict_proba(XA, y)
        pB, _  = in_sample_predict_proba(XB, y)
        pAB, _ = in_sample_predict_proba(XAB, y)

        aucA  = roc_auc_score(y, pA)
        aucB  = roc_auc_score(y, pB)
        aucAB = roc_auc_score(y, pAB)
    else:
        raise ValueError("mode must be 'cv' or 'insample'")

    dA  = auc0 - aucA
    dB  = auc0 - aucB
    dAB = auc0 - aucAB
    return dAB - (dA + dB), dict(auc0=auc0, aucA=aucA, aucB=aucB, aucAB=aucAB, dA=dA, dB=dB, dAB=dAB)

def perm_pvalue_synergy(X, y, splits, i, j, mode="cv", n_perm=200, seed=123):
    rng = np.random.default_rng(seed)
    syn_obs, _ = auc_synergy(X, y, splits, i, j, mode=mode)
    null = np.empty(n_perm, dtype=float)
    for k in range(n_perm):
        y_perm = rng.permutation(y)
        syn_k, _ = auc_synergy(X, y_perm, splits, i, j, mode=mode)
        null[k] = syn_k
    # one-sided: cooperative = negative synergy
    kk = int((null <= syn_obs).sum())
    p = (kk + 1) / (n_perm + 1)
    return syn_obs, p, null

# ----------------------------
# Sweep parameters
# ----------------------------
n_total = 89
p = 20
pair = (0, 1)  # planted cooperating features A,B
n_pos_list = [9, 15, 25, 40]
gamma_list = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
n_reps = 50  # bump to 100 after sanity check

results = []
rng_master = np.random.default_rng(20260214)

for n_pos in n_pos_list:
    for gamma in gamma_list:
        syn_cv = []
        syn_in = []
        base_auc_cv = []
        base_auc_in = []

        for r in range(n_reps):
            rng = np.random.default_rng(rng_master.integers(0, 2**32 - 1))
            y = make_balanced_labels(n_total=n_total, n_pos=n_pos, rng=rng)
            X = simulate_X_with_interaction(y, p=p, gamma=gamma, rng=rng)

            skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
            splits = list(skf.split(X, y))

            # CV synergy
            s_cv, info_cv = auc_synergy(X, y, splits, pair[0], pair[1], mode="cv")
            syn_cv.append(s_cv)
            base_auc_cv.append(info_cv["auc0"])

            # In-sample synergy (for failure-mode comparison)
            s_in, info_in = auc_synergy(X, y, splits, pair[0], pair[1], mode="insample")
            syn_in.append(s_in)
            base_auc_in.append(info_in["auc0"])

        results.append({
            "n_pos": n_pos,
            "gamma": gamma,
            "mean_auc_cv": float(np.mean(base_auc_cv)),
            "mean_auc_insample": float(np.mean(base_auc_in)),
            "mean_syn_cv": float(np.mean(syn_cv)),
            "sd_syn_cv": float(np.std(syn_cv)),
            "mean_syn_insample": float(np.mean(syn_in)),
            "sd_syn_insample": float(np.std(syn_in)),
            "frac_syn_cv_neg": float(np.mean(np.array(syn_cv) < 0)),
            "frac_syn_insample_neg": float(np.mean(np.array(syn_in) < 0)),
        })

sweep_df = pd.DataFrame(results)
print(sweep_df)

# Save for plotting later
sweep_df.to_csv("SIM_AUC_synergy_power_sweep.csv", index=False)
print("\nSaved: SIM_AUC_synergy_power_sweep.csv")

# ----------------------------
# Diagnostic run: replicate the failure mode (single run with n_pos=9, gamma=0.4)
# ----------------------------
diag_n_pos = 9
diag_gamma = 0.4
rng = np.random.default_rng(777)
y = make_balanced_labels(n_total=n_total, n_pos=diag_n_pos, rng=rng)
X = simulate_X_with_interaction(y, p=p, gamma=diag_gamma, rng=rng)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
splits = list(skf.split(X, y))

syn_cv, info_cv = auc_synergy(X, y, splits, pair[0], pair[1], mode="cv")
syn_in, info_in = auc_synergy(X, y, splits, pair[0], pair[1], mode="insample")

print("\n=== DIAGNOSTIC SINGLE RUN ===")
print("n_pos:", diag_n_pos, "gamma:", diag_gamma)
print("In-sample baseline AUC:", info_in["auc0"], "Synergy:", syn_in)
print("CV baseline AUC:", info_cv["auc0"], "Synergy:", syn_cv)

# Optional: quick permutation p-values (keep n_perm small for speed)
syn_cv_obs, p_cv, _ = perm_pvalue_synergy(X, y, splits, pair[0], pair[1], mode="cv", n_perm=200, seed=1)
syn_in_obs, p_in, _ = perm_pvalue_synergy(X, y, splits, pair[0], pair[1], mode="insample", n_perm=200, seed=1)
print("Permutation p (in-sample):", p_in)
print("Permutation p (CV):", p_cv)

    n_pos  gamma  mean_auc_cv  mean_auc_insample  mean_syn_cv  sd_syn_cv  \
0       9    0.0     0.709639           0.981972     0.029639   0.050998
1       9    0.1     0.700222           0.978806     0.058722   0.074238
2       9    0.2     0.689056           0.978444     0.059639   0.053195
3       9    0.3     0.724889           0.978833     0.083167   0.080832
4       9    0.4     0.710194           0.979944     0.102389   0.093043
5       9    0.5     0.699611           0.976861     0.119611   0.087193
6      15    0.0     0.715514           0.954090     0.046937   0.043515
7      15    0.1     0.720342           0.953441     0.058486   0.051752
8      15    0.2     0.728324           0.954955     0.084991   0.067405
9      15    0.3     0.726919           0.959928     0.092162   0.062822
10     15    0.4     0.703099           0.950486     0.109640   0.090863
11     15    0.5     0.731892           0.956378     0.132468   0.097024
12     25    0.0     0.747613           0.933412     0.065637   0.043494
13     25    0.1     0.728500           0.928575     0.091525   0.050748
14     25    0.2     0.755800           0.936425     0.109950   0.060488
15     25    0.3     0.748825           0.935963     0.118613   0.067265
16     25    0.4     0.726525           0.928013     0.141238   0.066524
17     25    0.5     0.721138           0.926013     0.128575   0.072997
18     40    0.0     0.765480           0.924092     0.077408   0.048044
19     40    0.1     0.755398           0.922694     0.107490   0.046353
20     40    0.2     0.758194           0.922071     0.118592   0.060728
21     40    0.3     0.738367           0.909765     0.134255   0.060385
22     40    0.4     0.744531           0.915704     0.130378   0.058488
23     40    0.5     0.731276           0.907888     0.157541   0.056136

    mean_syn_insample  sd_syn_insample  frac_syn_cv_neg  frac_syn_insample_neg
0            0.017417         0.023899             0.28                   0.26
1            0.027361         0.033272             0.16                   0.20
2            0.031778         0.029960             0.06                   0.10
3            0.031278         0.026052             0.10                   0.06
4            0.036889         0.033198             0.10                   0.08
5            0.041500         0.034041             0.04                   0.06
6            0.033640         0.028761             0.06                   0.08
7            0.037117         0.027411             0.12                   0.08
8            0.042595         0.033350             0.08                   0.06
9            0.046613         0.030051             0.02                   0.02
10           0.056829         0.043359             0.02                   0.04
11           0.065369         0.045051             0.02                   0.00
12           0.041937         0.029264             0.06                   0.06
13           0.052750         0.029783             0.02                   0.04
14           0.068937         0.036667             0.02                   0.00
15           0.067275         0.034533             0.02                   0.02
16           0.075962         0.034520             0.00                   0.00
17           0.074100         0.038506             0.02                   0.00
18           0.049388         0.025972             0.02                   0.00
19           0.059173         0.028301             0.00                   0.00
20           0.069765         0.030892             0.00                   0.00
21           0.078816         0.036550             0.00                   0.00
22           0.076663         0.033875             0.00                   0.00
23           0.090745         0.036717             0.00                   0.00

Saved: SIM_AUC_synergy_power_sweep.csv

=== DIAGNOSTIC SINGLE RUN ===
n_pos: 9 gamma: 0.4
In-sample baseline AUC: 0.9583333333333334 Synergy: 0.004166666666666763
CV baseline AUC: 0.5375 Synergy: 0.04583333333333328
Permutation p (in-sample): 0.8109452736318408
Permutation p (CV): 0.9800995024875622

In [46]:
import numpy as np

def simulate_Xy_logistic_interaction_topk(
    n_total=89,
    n_pos=9,
    p=20,
    wA=1.0,
    wB=1.0,
    gamma=0.0,
    rho_AB=0.0,
    noise=1.0,
    rng=None,
):
    """
    Generate X ~ MVN(0, Σ) with correlation rho_AB between features 0 and 1 (A,B).
    Define probability p_i = sigmoid(wA*A + wB*B + gamma*A*B).
    Set y=1 for top n_pos by p_i (deterministic prevalence control).
    """
    rng = np.random.default_rng() if rng is None else rng

    # Covariance for p features, correlate only A/B
    Sigma = np.eye(p) * (noise**2)
    Sigma[0, 1] = Sigma[1, 0] = rho_AB * (noise**2)

    X = rng.multivariate_normal(mean=np.zeros(p), cov=Sigma, size=n_total)

    A = X[:, 0]
    B = X[:, 1]

    eta = wA * A + wB * B + gamma * (A * B)
    prob = 1.0 / (1.0 + np.exp(-eta))

    # Force exactly n_pos positives (largest probabilities)
    idx = np.argsort(prob)[::-1]
    y = np.zeros(n_total, dtype=int)
    y[idx[:n_pos]] = 1

    return X, y, prob

In [47]:
def simulate_cooperative(n_total, n_pos, p, gamma, w_main=1.0, noise=1.0, rng=None):
    rng = rng or np.random.default_rng()
    X = rng.normal(0, noise, size=(n_total, p))
    A, B = X[:, 0], X[:, 1]
    
    # Class probability from logistic model WITH interaction
    eta = w_main * A + w_main * B + gamma * A * B
    prob = 1 / (1 + np.exp(-eta))
    
    # Fix class counts by taking top n_pos by probability
    threshold_idx = np.argsort(prob)[-n_pos:]
    y = np.zeros(n_total, dtype=int)
    y[threshold_idx] = 1
    
    return X, y

In [48]:
X, y, prob = simulate_Xy_logistic_interaction_topk(
    n_total=n_total,
    n_pos=n_pos,
    p=p,
    wA=1.0,
    wB=1.0,
    gamma=gamma,
    rho_AB=0.0,   # you can also sweep this later
    noise=1.0,
    rng=rng
)

In [49]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# ----------------------------
# Clean cooperative generator
# ----------------------------
def simulate_cooperative_topk(n_total, n_pos, p, gamma, w_main=1.0, noise=1.0, rho_AB=0.0, rng=None):
    rng = np.random.default_rng() if rng is None else rng

    # Optional correlation between A and B
    Sigma = np.eye(p) * (noise**2)
    Sigma[0, 1] = Sigma[1, 0] = rho_AB * (noise**2)

    X = rng.multivariate_normal(np.zeros(p), Sigma, size=n_total)
    A, B = X[:, 0], X[:, 1]

    eta = w_main * A + w_main * B + gamma * (A * B)
    prob = 1.0 / (1.0 + np.exp(-eta))

    # Force exactly n_pos positives
    idx = np.argsort(prob)[::-1]
    y = np.zeros(n_total, dtype=int)
    y[idx[:n_pos]] = 1
    return X, y, prob

# ----------------------------
# Modeling helpers
# ----------------------------
def cv_predict_proba(X, y, splits, C=1.0, seed=0):
    probs = np.zeros(len(y), dtype=float)
    for tr, te in splits:
        clf = LogisticRegression(
            C=C, penalty="l2", solver="lbfgs", max_iter=5000,
            class_weight="balanced", random_state=seed
        )
        clf.fit(X[tr], y[tr])
        probs[te] = clf.predict_proba(X[te])[:, 1]
    return probs

def in_sample_predict_proba(X, y, C=1.0, seed=0):
    clf = LogisticRegression(
        C=C, penalty="l2", solver="lbfgs", max_iter=5000,
        class_weight="balanced", random_state=seed
    )
    clf.fit(X, y)
    return clf.predict_proba(X)[:, 1]

def auc_synergy(X, y, splits, i, j, mode="cv"):
    if mode == "cv":
        p0 = cv_predict_proba(X, y, splits)
        auc0 = roc_auc_score(y, p0)

        XA  = np.delete(X, i, axis=1)
        XB  = np.delete(X, j, axis=1)
        XAB = np.delete(X, [i, j], axis=1)

        pA  = cv_predict_proba(XA, y, splits)
        pB  = cv_predict_proba(XB, y, splits)
        pAB = cv_predict_proba(XAB, y, splits)

        aucA  = roc_auc_score(y, pA)
        aucB  = roc_auc_score(y, pB)
        aucAB = roc_auc_score(y, pAB)

    elif mode == "insample":
        p0 = in_sample_predict_proba(X, y)
        auc0 = roc_auc_score(y, p0)

        XA  = np.delete(X, i, axis=1)
        XB  = np.delete(X, j, axis=1)
        XAB = np.delete(X, [i, j], axis=1)

        pA  = in_sample_predict_proba(XA, y)
        pB  = in_sample_predict_proba(XB, y)
        pAB = in_sample_predict_proba(XAB, y)

        aucA  = roc_auc_score(y, pA)
        aucB  = roc_auc_score(y, pB)
        aucAB = roc_auc_score(y, pAB)

    else:
        raise ValueError("mode must be 'cv' or 'insample'")

    dA  = auc0 - aucA
    dB  = auc0 - aucB
    dAB = auc0 - aucAB
    synergy = dAB - (dA + dB)
    return synergy, dict(auc0=auc0, aucA=aucA, aucB=aucB, aucAB=aucAB)

# ----------------------------
# Sweep
# ----------------------------
n_total = 89
p = 20
pair = (0, 1)  # A,B
n_pos_list = [9, 15, 25, 40]
gamma_list = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
n_reps = 50

rng_master = np.random.default_rng(20260214)
rows = []

for n_pos in n_pos_list:
    for gamma in gamma_list:
        syn_cv = []
        syn_in = []
        auc_cv = []
        auc_in = []

        for r in range(n_reps):
            rng = np.random.default_rng(rng_master.integers(0, 2**32 - 1))
            X, y, prob = simulate_cooperative_topk(
                n_total=n_total, n_pos=n_pos, p=p,
                gamma=gamma, w_main=1.0, noise=1.0, rho_AB=0.0, rng=rng
            )
            skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
            splits = list(skf.split(X, y))

            s_cv, info_cv = auc_synergy(X, y, splits, pair[0], pair[1], mode="cv")
            s_in, info_in = auc_synergy(X, y, splits, pair[0], pair[1], mode="insample")

            syn_cv.append(s_cv)
            syn_in.append(s_in)
            auc_cv.append(info_cv["auc0"])
            auc_in.append(info_in["auc0"])

        rows.append({
            "n_pos": n_pos,
            "gamma": gamma,
            "mean_auc_cv": float(np.mean(auc_cv)),
            "mean_auc_insample": float(np.mean(auc_in)),
            "mean_syn_cv": float(np.mean(syn_cv)),
            "sd_syn_cv": float(np.std(syn_cv)),
            "mean_syn_insample": float(np.mean(syn_in)),
            "sd_syn_insample": float(np.std(syn_in)),
            "frac_syn_cv_neg": float(np.mean(np.array(syn_cv) < 0)),
            "frac_syn_insample_neg": float(np.mean(np.array(syn_in) < 0)),
        })

sweep_df = pd.DataFrame(rows)
print(sweep_df)
sweep_df.to_csv("SIM_AUC_synergy_power_sweep_correct.csv", index=False)
print("\nSaved: SIM_AUC_synergy_power_sweep_correct.csv")

# ----------------------------
# Diagnostic single run (bridge figure)
# ----------------------------
diag_n_pos = 9
diag_gamma = 0.4
rng = np.random.default_rng(777)
X, y, prob = simulate_cooperative_topk(n_total, diag_n_pos, p, diag_gamma, rng=rng)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
splits = list(skf.split(X, y))

syn_cv, info_cv = auc_synergy(X, y, splits, pair[0], pair[1], mode="cv")
syn_in, info_in = auc_synergy(X, y, splits, pair[0], pair[1], mode="insample")

print("\n=== DIAGNOSTIC SINGLE RUN (correct generator) ===")
print("n_pos:", diag_n_pos, "gamma:", diag_gamma)
print("In-sample baseline AUC:", info_in["auc0"], "Synergy:", syn_in)
print("CV baseline AUC:", info_cv["auc0"], "Synergy:", syn_cv)

    n_pos  gamma  mean_auc_cv  mean_auc_insample  mean_syn_cv  sd_syn_cv  \
0       9    0.0     0.930722           1.000000     0.048333   0.065396
1       9    0.1     0.912028           0.999806     0.022111   0.065918
2       9    0.2     0.907639           0.999806     0.060806   0.061208
3       9    0.3     0.897639           0.999917     0.044972   0.068771
4       9    0.4     0.915778           0.999694     0.054750   0.078355
5       9    0.5     0.906639           0.999389     0.048333   0.062498
6      15    0.0     0.934216           0.999802     0.032234   0.063803
7      15    0.1     0.941027           0.999784     0.037261   0.057516
8      15    0.2     0.943712           0.999766     0.052414   0.067422
9      15    0.3     0.927784           0.999532     0.060847   0.066623
10     15    0.4     0.929135           0.999604     0.052703   0.075132
11     15    0.5     0.912216           0.999333     0.039820   0.057714
12     25    0.0     0.947388           0.999687     0.030200   0.063503
13     25    0.1     0.948063           0.999850     0.038475   0.069811
14     25    0.2     0.945600           0.999263     0.039813   0.060047
15     25    0.3     0.947288           0.999450     0.048450   0.068379
16     25    0.4     0.935900           0.998663     0.037263   0.062390
17     25    0.5     0.934800           0.998362     0.067213   0.055802
18     40    0.0     0.945337           0.999633     0.030337   0.059225
19     40    0.1     0.951806           0.999765     0.030878   0.059066
20     40    0.2     0.950908           0.999612     0.044765   0.073982
21     40    0.3     0.944224           0.998867     0.039276   0.064714
22     40    0.4     0.936939           0.998235     0.044102   0.057795
23     40    0.5     0.928592           0.996235     0.036051   0.058903

    mean_syn_insample  sd_syn_insample  frac_syn_cv_neg  frac_syn_insample_neg
0            0.057778         0.039071             0.16                   0.02
1            0.034556         0.029564             0.34                   0.06
2            0.045444         0.027430             0.18                   0.02
3            0.050167         0.037377             0.20                   0.04
4            0.051972         0.032668             0.32                   0.06
5            0.041528         0.030443             0.18                   0.08
6            0.059874         0.033247             0.30                   0.00
7            0.059568         0.026486             0.24                   0.00
8            0.070919         0.035560             0.24                   0.00
9            0.067171         0.045427             0.12                   0.00
10           0.069694         0.040992             0.30                   0.02
11           0.065405         0.030921             0.26                   0.02
12           0.056800         0.036075             0.36                   0.10
13           0.066650         0.043988             0.32                   0.08
14           0.062225         0.037730             0.26                   0.02
15           0.065975         0.039824             0.28                   0.04
16           0.059637         0.033437             0.26                   0.02
17           0.072275         0.042326             0.12                   0.00
18           0.052224         0.034916             0.24                   0.06
19           0.055031         0.033992             0.26                   0.06
20           0.059867         0.046650             0.30                   0.10
21           0.050122         0.041748             0.30                   0.08
22           0.057704         0.035639             0.22                   0.06
23           0.045663         0.035226             0.30                   0.10

Saved: SIM_AUC_synergy_power_sweep_correct.csv

=== DIAGNOSTIC SINGLE RUN (correct generator) ===
n_pos: 9 gamma: 0.4
In-sample baseline AUC: 1.0 Synergy: 0.10972222222222228
CV baseline AUC: 0.8486111111111111 Synergy: 0.036111111111111094

In [50]:
# Quick test: just 2 reps, 1 n_pos, 2 gammas
n_pos_list = [9]
gamma_list = [0.0, 0.4]
n_reps = 2

In [51]:
def simulate_pure_interaction(n_total, n_pos, p, gamma, noise=1.0, rng=None):
    rng = np.random.default_rng() if rng is None else rng

    X = rng.normal(0, noise, size=(n_total, p))
    A, B = X[:, 0], X[:, 1]

    eta = gamma * (A * B)
    prob = 1 / (1 + np.exp(-eta))

    idx = np.argsort(prob)[::-1]
    y = np.zeros(n_total, dtype=int)
    y[idx[:n_pos]] = 1

    return X, y

In [52]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# ----------------------------
# Shared evaluation: CV AUC synergy + CV margin-depth synergy
# ----------------------------
def cv_splits(X, y, n_splits=5, seed=0):
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    return list(skf.split(X, y))

def cv_probs_and_margins(X, y, splits, C=1.0):
    """
    Out-of-fold predicted probs and signed margins for each sample.
    Margin = (w^T x + b)/||w||
    """
    n = len(y)
    probs = np.zeros(n, dtype=float)
    margins = np.zeros(n, dtype=float)

    for tr, te in splits:
        clf = LogisticRegression(
            C=C, solver="lbfgs", max_iter=5000,
            class_weight="balanced", random_state=0
        )
        clf.fit(X[tr], y[tr])
        probs[te] = clf.predict_proba(X[te])[:, 1]

        w = clf.coef_[0]
        b = clf.intercept_[0]
        denom = np.linalg.norm(w) + 1e-12
        margins[te] = (X[te] @ w + b) / denom

    return probs, margins

def depth_from_margins(margins, y, which=1):
    """Mean signed margin for a class (default: positives y==1)."""
    return float(np.mean(margins[y == which]))

def auc_synergy_cv(X, y, splits, i, j):
    # baseline
    p0, m0 = cv_probs_and_margins(X, y, splits)
    auc0 = roc_auc_score(y, p0)

    # single removals
    XA = np.delete(X, i, axis=1)
    XB = np.delete(X, j, axis=1)
    XAB = np.delete(X, [i, j], axis=1)

    pA, _ = cv_probs_and_margins(XA, y, splits)
    pB, _ = cv_probs_and_margins(XB, y, splits)
    pAB,_ = cv_probs_and_margins(XAB, y, splits)

    aucA = roc_auc_score(y, pA)
    aucB = roc_auc_score(y, pB)
    aucAB= roc_auc_score(y, pAB)

    dA  = auc0 - aucA
    dB  = auc0 - aucB
    dAB = auc0 - aucAB
    S = dAB - (dA + dB)
    return float(S), dict(auc0=auc0, dA=dA, dB=dB, dAB=dAB)

def depth_synergy_cv(X, y, splits, i, j):
    # baseline depth on positives
    _, m0 = cv_probs_and_margins(X, y, splits)
    D0 = depth_from_margins(m0, y, which=1)

    XA = np.delete(X, i, axis=1)
    XB = np.delete(X, j, axis=1)
    XAB = np.delete(X, [i, j], axis=1)

    _, mA  = cv_probs_and_margins(XA, y, splits)
    _, mB  = cv_probs_and_margins(XB, y, splits)
    _, mAB = cv_probs_and_margins(XAB, y, splits)

    DA  = depth_from_margins(mA,  y, which=1)
    DB  = depth_from_margins(mB,  y, which=1)
    DAB = depth_from_margins(mAB, y, which=1)

    dA  = D0 - DA
    dB  = D0 - DB
    dAB = D0 - DAB
    S = dAB - (dA + dB)
    return float(S), dict(D0=D0, dA=dA, dB=dB, dAB=dAB)

# ----------------------------
# Label helper: fixed n_pos (top-k on score) to mimic scarcity scenarios
# ----------------------------
def labels_topk(score, n_pos):
    idx = np.argsort(score)[::-1]
    y = np.zeros(len(score), dtype=int)
    y[idx[:n_pos]] = 1
    return y

# ----------------------------
# Panel generators (all return X,y with p>=2; planted pair is (0,1))
# ----------------------------
def gen_independence(n=200, n_pos=50, p=20, eff=1.0, noise=1.0, rng=None):
    """Two independent additive signals. Expect synergy ~ 0."""
    rng = np.random.default_rng() if rng is None else rng
    X = rng.normal(0, noise, size=(n, p))
    score = eff*X[:,0] + eff*X[:,1] + rng.normal(0, noise, size=n)
    y = labels_topk(score, n_pos)
    return X, y

def gen_redundancy(n=200, n_pos=50, p=20, eff=1.0, rho=0.9, noise=1.0, rng=None):
    """
    Two highly correlated features carrying overlapping signal.
    Expect sub-additive loss => synergy < 0 (redundancy).
    """
    rng = np.random.default_rng() if rng is None else rng
    X = rng.normal(0, noise, size=(n, p))
    # Make feature 1 a noisy copy of feature 0
    X[:,1] = rho*X[:,0] + np.sqrt(max(1e-12, 1-rho**2))*rng.normal(0, noise, size=n)
    score = eff*X[:,0] + eff*X[:,1] + rng.normal(0, noise, size=n)
    y = labels_topk(score, n_pos)
    return X, y

def gen_complementarity(n=200, n_pos=50, p=20, eff=1.0, anticorr=1.0, noise=1.0, rng=None):
    """
    Joint-essentiality: signal lives on diagonal (A+B), but anti-correlated jitter
    makes A and B individually unreliable. Expect super-additive loss => synergy > 0.
    """
    rng = np.random.default_rng() if rng is None else rng
    X = rng.normal(0, noise, size=(n, p))

    # Create a diagonal "joint axis" shift that defines class
    base_score = eff*(X[:,0] + X[:,1]) + rng.normal(0, noise, size=n)
    y = labels_topk(base_score, n_pos)

    # Anti-correlated noise applied to positives to wash out marginals but preserve joint axis
    z = rng.normal(0, anticorr, size=(y==1).sum())
    X[y==1,0] += z
    X[y==1,1] -= z
    return X, y

# ----------------------------
# Run Panel A–C: synergy distributions (CV)
# ----------------------------
def run_panel(generator, name, n=200, n_pos=50, p=20, reps=50, **kwargs):
    rng_master = np.random.default_rng(20260214)
    rows=[]
    for r in range(reps):
        rng = np.random.default_rng(rng_master.integers(0,2**32-1))
        X, y = generator(n=n, n_pos=n_pos, p=p, rng=rng, **kwargs)
        splits = cv_splits(X, y, n_splits=5, seed=0)
        S_auc, info_auc = auc_synergy_cv(X, y, splits, 0, 1)
        S_dep, info_dep = depth_synergy_cv(X, y, splits, 0, 1)
        rows.append({
            "regime": name,
            "rep": r,
            "auc0": info_auc["auc0"],
            "S_auc": S_auc,
            "S_depth": S_dep
        })
    return pd.DataFrame(rows)

df_A = run_panel(gen_independence, "Independence", eff=1.0)
df_B = run_panel(gen_redundancy, "Redundancy", eff=1.0, rho=0.9)
df_C = run_panel(gen_complementarity, "Complementarity", eff=1.0, anticorr=1.0)

df_ABC = pd.concat([df_A, df_B, df_C], ignore_index=True)

# Summaries (this is what you narrate in Fig 2 A–C)
summary = df_ABC.groupby("regime").agg(
    mean_auc0=("auc0","mean"),
    mean_S_auc=("S_auc","mean"),
    frac_S_auc_pos=("S_auc", lambda x: float(np.mean(x>0))),
    mean_S_depth=("S_depth","mean"),
    frac_S_depth_pos=("S_depth", lambda x: float(np.mean(x>0))),
).reset_index()

print(summary)
df_ABC.to_csv("FIG2_ABC_synergy_distributions.csv", index=False)
print("Saved: FIG2_ABC_synergy_distributions.csv")

# ----------------------------
# Panel D: magnitude scaling (Complementarity only)
# ----------------------------
eff_list = [0.25, 0.5, 0.75, 1.0, 1.25, 1.5]
rows=[]
for eff in eff_list:
    df_tmp = run_panel(gen_complementarity, "Complementarity", eff=eff, anticorr=1.0, reps=50)
    rows.append({
        "eff": eff,
        "mean_auc0": float(df_tmp["auc0"].mean()),
        "mean_S_auc": float(df_tmp["S_auc"].mean()),
        "mean_S_depth": float(df_tmp["S_depth"].mean())
    })
df_D = pd.DataFrame(rows)
print("\nMagnitude scaling (Panel D):")
print(df_D)
df_D.to_csv("FIG2_D_magnitude_scaling.csv", index=False)
print("Saved: FIG2_D_magnitude_scaling.csv")

            regime  mean_auc0  mean_S_auc  frac_S_auc_pos  mean_S_depth  \
0  Complementarity   0.863435   -0.037421            0.16      0.082182
1     Independence   0.862933    0.076675            1.00      0.222728
2       Redundancy   0.906531    0.389603            1.00      0.579421

   frac_S_depth_pos
0              0.88
1              1.00
2              1.00
Saved: FIG2_ABC_synergy_distributions.csv

Magnitude scaling (Panel D):
    eff  mean_auc0  mean_S_auc  mean_S_depth
0  0.25   0.592040   -0.021296     -0.036050
1  0.50   0.721808   -0.029904     -0.011039
2  0.75   0.809163   -0.032835      0.039330
3  1.00   0.863435   -0.037421      0.082182
4  1.25   0.894712   -0.036168      0.116344
5  1.50   0.914611   -0.041227      0.150237
Saved: FIG2_D_magnitude_scaling.csv

In [53]:
import numpy as np
import pandas as pd
from scipy.stats import mannwhitneyu

def gen_spec_vs_maint(n=200, n_pos=50, p=10, rng=None):
    rng = np.random.default_rng() if rng is None else rng
    y = np.zeros(n, dtype=int)
    y[:n_pos] = 1
    rng.shuffle(y)

    X = np.zeros((n, p), dtype=float)

    # Feature 0: "Specification" — large mean shift, high variance (diff strong, stability weak)
    X[:,0] = rng.normal(0, 3.0, size=n) + y*2.0

    # Feature 1: "Maintenance" — smaller mean shift, low variance (diff modest, stability strong)
    X[:,1] = rng.normal(0, 0.5, size=n) + y*0.8

    # Other noise features
    X[:,2:] = rng.normal(0, 1.0, size=(n, p-2))
    return X, y

# One run + compute diff rank and ΔDepth rank by leave-one-out (CV depth)
rng = np.random.default_rng(123)
X, y = gen_spec_vs_maint(rng=rng)
splits = cv_splits(X, y, n_splits=5, seed=0)

# Differential (Mann–Whitney)
diff_rows=[]
for k in range(X.shape[1]):
    hi = X[y==1, k]; lo = X[y==0, k]
    stat, pval = mannwhitneyu(hi, lo, alternative="two-sided")
    diff_rows.append((k, hi.mean()-lo.mean(), pval))
diff_df = pd.DataFrame(diff_rows, columns=["feat","Δmean","p"]).sort_values("Δmean", ascending=False)

# ΔDepth leave-one-out (CV depth)
# baseline depth
_, m0 = cv_probs_and_margins(X, y, splits)
D0 = depth_from_margins(m0, y, which=1)

dd_rows=[]
for k in range(X.shape[1]):
    Xk = np.delete(X, k, axis=1)
    _, mk = cv_probs_and_margins(Xk, y, splits)
    Dk = depth_from_margins(mk, y, which=1)
    dd = D0 - Dk
    dd_rows.append((k, dd))
dd_df = pd.DataFrame(dd_rows, columns=["feat","ΔDepth"]).sort_values("ΔDepth", ascending=False)

print("Top differential features:")
print(diff_df.head(5))
print("\nTop maintenance (ΔDepth) features:")
print(dd_df.head(5))

# Save combined for supplement plotting
out = diff_df.merge(dd_df, on="feat")
out.to_csv("SUPP_spec_vs_maint_sim.csv", index=False)
print("\nSaved: SUPP_spec_vs_maint_sim.csv")

Top differential features:
   feat     Δmean             p
0     0  2.198609  3.785305e-06
1     1  0.846904  6.345128e-15
2     2  0.589882  2.776021e-04
5     5  0.346718  6.772306e-02
4     4  0.160589  3.996857e-01

Top maintenance (ΔDepth) features:
   feat    ΔDepth
0     0  0.133670
2     2  0.051736
1     1  0.047044
8     8  0.001431
3     3  0.001356

Saved: SUPP_spec_vs_maint_sim.csv

In [54]:
print(info_auc)

NameError: name 'info_auc' is not defined

In [55]:
import numpy as np

# One replicate per regime, print the ablation components directly
def inspect_one(generator, name, seed=0, **kwargs):
    rng = np.random.default_rng(seed)
    X, y = generator(n=200, n_pos=50, p=20, rng=rng, **kwargs)
    splits = cv_splits(X, y, n_splits=5, seed=0)

    S_auc, info_auc = auc_synergy_cv(X, y, splits, 0, 1)
    S_dep, info_dep = depth_synergy_cv(X, y, splits, 0, 1)

    print(f"\n=== {name} ===")
    print("AUC0:", info_auc["auc0"])
    print("dA, dB, dAB:", info_auc["dA"], info_auc["dB"], info_auc["dAB"])
    print("S_auc:", S_auc)

    print("D0:", info_dep["D0"])
    print("dA, dB, dAB:", info_dep["dA"], info_dep["dB"], info_dep["dAB"])
    print("S_depth:", S_dep)

# Run
inspect_one(gen_independence, "Independence", eff=1.0)
inspect_one(gen_redundancy, "Redundancy", eff=1.0, rho=0.9)
inspect_one(gen_complementarity, "Complementarity", eff=1.0, anticorr=1.0)

=== Independence ===
AUC0: 0.7952
dA, dB, dAB: 0.07373333333333332 0.12440000000000007 0.23733333333333329
S_auc: 0.0391999999999999
D0: 0.3845567776886281
dA, dB, dAB: 0.13195491854002023 0.24412459720060598 0.4767142959481626
S_depth: 0.10063478020753641

=== Redundancy ===
AUC0: 0.8864000000000001
dA, dB, dAB: 0.004533333333333389 0.03720000000000012 0.44186666666666674
S_auc: 0.40013333333333323
D0: 0.562458037495901
dA, dB, dAB: 0.08841055060876085 0.16267183472360364 0.8342941409612423
S_depth: 0.5832117556288778

=== Complementarity ===
AUC0: 0.7982666666666667
dA, dB, dAB: 0.12573333333333325 0.1572 0.24039999999999995
S_auc: -0.04253333333333331
D0: 0.38845336183669515
dA, dB, dAB: 0.22309261110384604 0.2959033125727485 0.48061088009622965
S_depth: -0.038385043580364875

In [56]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Reuse your cooperative generator (joint essentiality)
def simulate_joint_axis(n_total, n_pos, p, eff, anticorr=1.0, noise=1.0, rng=None):
    rng = np.random.default_rng() if rng is None else rng
    X = rng.normal(0, noise, size=(n_total, p))

    # Base score along diagonal
    base_score = eff * (X[:,0] + X[:,1]) + rng.normal(0, noise, size=n_total)

    # Top-k labeling to control prevalence
    idx = np.argsort(base_score)[::-1]
    y = np.zeros(n_total, dtype=int)
    y[idx[:n_pos]] = 1

    # Anti-correlated jitter to weaken marginals
    z = rng.normal(0, anticorr, size=n_pos)
    X[y==1, 0] += z
    X[y==1, 1] -= z

    return X, y

def cv_auc_and_synergy(X, y, n_splits=5, seed=0, n_perm=200):
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    splits = list(skf.split(X, y))

    # Baseline CV AUC
    probs = np.zeros(len(y))
    for tr, te in splits:
        clf = LogisticRegression(C=1.0, solver="lbfgs", max_iter=5000,
                                 class_weight="balanced", random_state=0)
        clf.fit(X[tr], y[tr])
        probs[te] = clf.predict_proba(X[te])[:,1]
    auc0 = roc_auc_score(y, probs)

    # Synergy for pair (0,1)
    def auc_cv(X_local, y_local):
        probs_local = np.zeros(len(y_local))
        for tr, te in splits:
            clf = LogisticRegression(C=1.0, solver="lbfgs", max_iter=5000,
                                     class_weight="balanced", random_state=0)
            clf.fit(X_local[tr], y_local[tr])
            probs_local[te] = clf.predict_proba(X_local[te])[:,1]
        return roc_auc_score(y_local, probs_local)

    XA = np.delete(X, 0, axis=1)
    XB = np.delete(X, 1, axis=1)
    XAB = np.delete(X, [0,1], axis=1)

    aucA = auc_cv(XA, y)
    aucB = auc_cv(XB, y)
    aucAB = auc_cv(XAB, y)

    dA = auc0 - aucA
    dB = auc0 - aucB
    dAB = auc0 - aucAB
    S = dAB - (dA + dB)

    # Permutation p-value (one-sided: S > 0 = joint essentiality)
    rng = np.random.default_rng(seed+1)
    null = np.zeros(n_perm)
    for k in range(n_perm):
        y_perm = rng.permutation(y)
        # recompute only synergy numerator for speed
        probs_perm = np.zeros(len(y_perm))
        for tr, te in splits:
            clf = LogisticRegression(C=1.0, solver="lbfgs", max_iter=5000,
                                     class_weight="balanced", random_state=0)
            clf.fit(X[tr], y_perm[tr])
            probs_perm[te] = clf.predict_proba(X[te])[:,1]
        auc0p = roc_auc_score(y_perm, probs_perm)

        # pair removal
        aucAp = auc_cv(XA, y_perm)
        aucBp = auc_cv(XB, y_perm)
        aucABp = auc_cv(XAB, y_perm)

        dAp = auc0p - aucAp
        dBp = auc0p - aucBp
        dABp = auc0p - aucABp
        null[k] = dABp - (dAp + dBp)

    pval = (np.sum(null >= S) + 1) / (n_perm + 1)
    return auc0, S, pval

# ----------------------------
# Sweep grid
# ----------------------------
n_total = 89
p = 20
n_pos_list = [9, 15, 25, 40, 60]
eff_list = [0.5, 0.75, 1.0, 1.25, 1.5]
reps = 30

rows = []
rng_master = np.random.default_rng(20260214)

for n_pos in n_pos_list:
    for eff in eff_list:
        det = []
        aucs = []
        for r in range(reps):
            rng = np.random.default_rng(rng_master.integers(0,2**32-1))
            X, y = simulate_joint_axis(n_total, n_pos, p, eff, rng=rng)
            auc0, S, pval = cv_auc_and_synergy(X, y)
            aucs.append(auc0)
            det.append((S > 0) and (pval < 0.05))

        rows.append({
            "n_pos": n_pos,
            "eff": eff,
            "mean_auc_cv": float(np.mean(aucs)),
            "det_prob": float(np.mean(det))
        })

power_df = pd.DataFrame(rows)
print(power_df)
power_df.to_csv("FIG3_power_grid.csv", index=False)
print("\nSaved: FIG3_power_grid.csv")

# Identify approximate 50% detection threshold
threshold_rows = power_df[power_df["det_prob"] >= 0.5]
print("\nRows with >=50% detection:")
print(threshold_rows.sort_values("mean_auc_cv"))

KeyboardInterrupt:

In [57]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

def simulate_joint_axis(n_total, n_pos, p, eff, anticorr=1.0, noise=1.0, rng=None):
    rng = np.random.default_rng() if rng is None else rng
    X = rng.normal(0, noise, size=(n_total, p))
    base_score = eff * (X[:,0] + X[:,1]) + rng.normal(0, noise, size=n_total)
    idx = np.argsort(base_score)[::-1]
    y = np.zeros(n_total, dtype=int)
    y[idx[:n_pos]] = 1
    z = rng.normal(0, anticorr, size=n_pos)
    X[y==1, 0] += z
    X[y==1, 1] -= z
    return X, y

def quick_synergy(X, y):
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
    splits = list(skf.split(X, y))
    
    def auc_cv(Xin):
        probs = np.zeros(len(y))
        for tr, te in splits:
            clf = LogisticRegression(C=1.0, solver="lbfgs", max_iter=5000,
                                     class_weight="balanced", random_state=0)
            clf.fit(Xin[tr], y[tr])
            probs[te] = clf.predict_proba(Xin[te])[:,1]
        return roc_auc_score(y, probs)
    
    auc0 = auc_cv(X)
    dA = auc0 - auc_cv(np.delete(X, 0, axis=1))
    dB = auc0 - auc_cv(np.delete(X, 1, axis=1))
    dAB = auc0 - auc_cv(np.delete(X, [0,1], axis=1))
    S = dAB - (dA + dB)
    return auc0, S

n_total = 89
p = 20
n_pos_list = [9, 15, 25, 40, 60]
eff_list = [0.5, 0.75, 1.0, 1.25, 1.5]
reps = 30
rows = []
rng_master = np.random.default_rng(20260214)

for n_pos in n_pos_list:
    for eff in eff_list:
        det = []
        aucs = []
        for r in range(reps):
            rng = np.random.default_rng(rng_master.integers(0, 2**32-1))
            X, y = simulate_joint_axis(n_total, n_pos, p, eff, rng=rng)
            auc0, S = quick_synergy(X, y)
            aucs.append(auc0)
            det.append(S < 0)
        rows.append({"n_pos": n_pos, "eff": eff,
                      "mean_auc_cv": float(np.mean(aucs)),
                      "det_prob": float(np.mean(det))})
        print(f"n_pos={n_pos} eff={eff} auc={np.mean(aucs):.3f} det={np.mean(det):.2f}")

power_df = pd.DataFrame(rows)
power_df.to_csv("FIG3_power_grid.csv", index=False)
print("\nDone. Saved FIG3_power_grid.csv")
print(power_df)

threshold_rows = power_df[power_df["det_prob"] >= 0.5]
print("\nRows with >=50% detection:")
print(threshold_rows.sort_values("mean_auc_cv"))

n_pos=9 eff=0.5 auc=0.692 det=0.83
n_pos=9 eff=0.75 auc=0.726 det=0.77
n_pos=9 eff=1.0 auc=0.798 det=0.83
n_pos=9 eff=1.25 auc=0.822 det=0.60
n_pos=9 eff=1.5 auc=0.841 det=0.77
n_pos=15 eff=0.5 auc=0.670 det=0.87
n_pos=15 eff=0.75 auc=0.762 det=0.87
n_pos=15 eff=1.0 auc=0.799 det=0.93
n_pos=15 eff=1.25 auc=0.818 det=0.87
n_pos=15 eff=1.5 auc=0.859 det=0.80
n_pos=25 eff=0.5 auc=0.671 det=0.90
n_pos=25 eff=0.75 auc=0.738 det=1.00
n_pos=25 eff=1.0 auc=0.819 det=0.83
n_pos=25 eff=1.25 auc=0.836 det=0.93
n_pos=25 eff=1.5 auc=0.867 det=0.97
n_pos=40 eff=0.5 auc=0.662 det=0.83
n_pos=40 eff=0.75 auc=0.737 det=0.93
n_pos=40 eff=1.0 auc=0.831 det=0.97
n_pos=40 eff=1.25 auc=0.849 det=0.87
n_pos=40 eff=1.5 auc=0.876 det=1.00
n_pos=60 eff=0.5 auc=0.668 det=1.00
n_pos=60 eff=0.75 auc=0.745 det=0.90
n_pos=60 eff=1.0 auc=0.807 det=0.97
n_pos=60 eff=1.25 auc=0.842 det=1.00
n_pos=60 eff=1.5 auc=0.852 det=0.97

Done. Saved FIG3_power_grid.csv
    n_pos   eff  mean_auc_cv  det_prob
0       9  0.50     0.692407  0.833333
1       9  0.75     0.725509  0.766667
2       9  1.00     0.798102  0.833333
3       9  1.25     0.821991  0.600000
4       9  1.50     0.840972  0.766667
5      15  0.50     0.670180  0.866667
6      15  0.75     0.761832  0.866667
7      15  1.00     0.798739  0.933333
8      15  1.25     0.818078  0.866667
9      15  1.50     0.858529  0.800000
10     25  0.50     0.671479  0.900000
11     25  0.75     0.738083  1.000000
12     25  1.00     0.819167  0.833333
13     25  1.25     0.835708  0.933333
14     25  1.50     0.866896  0.966667
15     40  0.50     0.662007  0.833333
16     40  0.75     0.737415  0.933333
17     40  1.00     0.831156  0.966667
18     40  1.25     0.848878  0.866667
19     40  1.50     0.875884  1.000000
20     60  0.50     0.668123  1.000000
21     60  0.75     0.744521  0.900000
22     60  1.00     0.806724  0.966667
23     60  1.25     0.842222  1.000000
24     60  1.50     0.852280  0.966667

Rows with >=50% detection:
    n_pos   eff  mean_auc_cv  det_prob
15     40  0.50     0.662007  0.833333
20     60  0.50     0.668123  1.000000
5      15  0.50     0.670180  0.866667
10     25  0.50     0.671479  0.900000
0       9  0.50     0.692407  0.833333
1       9  0.75     0.725509  0.766667
16     40  0.75     0.737415  0.933333
11     25  0.75     0.738083  1.000000
21     60  0.75     0.744521  0.900000
6      15  0.75     0.761832  0.866667
2       9  1.00     0.798102  0.833333
7      15  1.00     0.798739  0.933333
22     60  1.00     0.806724  0.966667
8      15  1.25     0.818078  0.866667
12     25  1.00     0.819167  0.833333
3       9  1.25     0.821991  0.600000
17     40  1.00     0.831156  0.966667
13     25  1.25     0.835708  0.933333
4       9  1.50     0.840972  0.766667
23     60  1.25     0.842222  1.000000
18     40  1.25     0.848878  0.866667
24     60  1.50     0.852280  0.966667
9      15  1.50     0.858529  0.800000
14     25  1.50     0.866896  0.966667
19     40  1.50     0.875884  1.000000

In [58]:
n_pos_list = [9, 15, 25]
eff_list = [0.05, 0.1, 0.15, 0.2, 0.3]
reps = 30
rows2 = []
rng_master = np.random.default_rng(99999)

for n_pos in n_pos_list:
    for eff in eff_list:
        det = []
        aucs = []
        for r in range(reps):
            rng = np.random.default_rng(rng_master.integers(0, 2**32-1))
            X, y = simulate_joint_axis(n_total, n_pos, p, eff, rng=rng)
            auc0, S = quick_synergy(X, y)
            aucs.append(auc0)
            det.append(S < 0)
        rows2.append({"n_pos": n_pos, "eff": eff,
                       "mean_auc_cv": float(np.mean(aucs)),
                       "det_prob": float(np.mean(det))})
        print(f"n_pos={n_pos} eff={eff} auc={np.mean(aucs):.3f} det={np.mean(det):.2f}")

power_df2 = pd.DataFrame(rows2)
print(power_df2)

n_pos=9 eff=0.05 auc=0.531 det=0.53
n_pos=9 eff=0.1 auc=0.489 det=0.37
n_pos=9 eff=0.15 auc=0.526 det=0.60
n_pos=9 eff=0.2 auc=0.525 det=0.57
n_pos=9 eff=0.3 auc=0.569 det=0.87
n_pos=15 eff=0.05 auc=0.537 det=0.53
n_pos=15 eff=0.1 auc=0.509 det=0.57
n_pos=15 eff=0.15 auc=0.550 det=0.53
n_pos=15 eff=0.2 auc=0.531 det=0.77
n_pos=15 eff=0.3 auc=0.598 det=0.77
n_pos=25 eff=0.05 auc=0.533 det=0.33
n_pos=25 eff=0.1 auc=0.474 det=0.60
n_pos=25 eff=0.15 auc=0.527 det=0.70
n_pos=25 eff=0.2 auc=0.534 det=0.67
n_pos=25 eff=0.3 auc=0.537 det=0.77
    n_pos   eff  mean_auc_cv  det_prob
0       9  0.05     0.531435  0.533333
1       9  0.10     0.489306  0.366667
2       9  0.15     0.525602  0.600000
3       9  0.20     0.525278  0.566667
4       9  0.30     0.568750  0.866667
5      15  0.05     0.537027  0.533333
6      15  0.10     0.508949  0.566667
7      15  0.15     0.550270  0.533333
8      15  0.20     0.531381  0.766667
9      15  0.30     0.598258  0.766667
10     25  0.05     0.533104  0.333333
11     25  0.10     0.474250  0.600000
12     25  0.15     0.527187  0.700000
13     25  0.20     0.534417  0.666667
14     25  0.30     0.537167  0.766667